<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_603d0aedba030',
			'title'                 => 'BannerWithContentOverlay',
			'fields'                => array(
				array(
					'key'               => 'field_603d0af8e3731',
					'label' => __( 'Zdjęcie', 'partners-site_v2' ),
					'name'              => 'img',
					'type'              => 'image',
					'instructions' => __( '(min. szerokość: 1920px, Zalecana szerokość: 3840px)<br>(min wysokość: 556px)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'format_banner',
					'label'             => 'Banner w formacie 16:90?',
					'name'              => 'format_banner',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'choices'           => array(
						'tak' => 'tak',

					),
					'allow_null'        => true,
					'multiple'          => false,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_603d0b15e3732',
					'label' => __( 'Nagłówek', 'partners-site_v2' ),
					'name'              => 'heading',
					'type'              => 'text',
					'instructions' => __( '(max. 46 znaków)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '46',
				),
				array(
					'key'               => 'field_603d0b1ce3733',
					'label'             => 'Opis',
					'name'              => 'description',
					'type'              => 'textarea',
					'instructions' => __( '(max. 330 znaków)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '330',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_603d0b25e3734',
					'label'             => 'Link',
					'name'              => 'link',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/banner-with-content-overlay',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
