<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_603d0aedba030',
			'title'                 => __('BannerWithContentOverlay', 'partners-site_v2'),
			'fields'                => array(
				array(
					'key'               => 'field_603d0af8e3731',
					'label' 			=> __( 'Photo', 'partners-site_v2' ),
					'name'              => 'img',
					'type'              => 'image',
					'instructions' 		=> __( '(min. width: 1920px, recommended width: 3840px)<br>(min. height: 556px)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'format_banner',
					'label'             => __('Banner in 16:9 aspect ratio?', 'partners-site_v2'),
					'name'              => 'format_banner',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'choices'           => array(
						'tak' => __('yes', 'partners-site_v2'),

					),
					'allow_null'        => true,
					'multiple'          => false,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_603d0b15e3732',
					'label'				=> __( 'Header', 'partners-site_v2' ),
					'name'              => 'heading',
					'type'              => 'text',
					'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 46),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '46',
				),
				array(
					'key'               => 'field_603d0b1ce3733',
					'label'             => __('Description', 'partners-site_v2' ),
					'name'              => 'description',
					'type'              => 'textarea',
					'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 330),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '330',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_603d0b25e3734',
					'label'             => __('Link', 'partners-site_v2'),
					'name'              => 'link',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/banner-with-content-overlay',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
