<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
		'key' => 'group_668ce0b523e0b',
		'title' => __( 'Blog posts component', 'partners-site_v2' ),
		'fields' => array(
			array(
				'key' => 'field_668d38d6cd64c',
				'label' => sprintf( __( 'Title: Part %s', 'partners-site_v2' ), 1),
				'name' => 'title_1',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => __( 'Black H2', 'partners-site_v2' ),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_668d3907cd64d',
				'label' => sprintf( __( 'Title: Part %s', 'partners-site_v2' ), 2),
				'name' => 'title_2',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => __( 'Gray text in the title', 'partners-site_v2' ),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_668d38d6cd64c',
							'operator' => '!=',
							'value' => '',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_668ce0b550649',
				'label' => __( 'Filter by tag', 'partners-site_v2' ),
				'name' => 'tags',
				'aria-label' => '',
				'type' => 'taxonomy',
				'instructions' => __( 'Show only posts with one of the tags', 'partners-site_v2' ),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'post_tag',
				'add_term' => 0,
				'save_terms' => 1,
				'load_terms' => 0,
				'return_format' => 'id',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'bidirectional' => 0,
				'multiple' => 1,
				'bidirectional_target' => array(),
			),
			array(
				'key' => 'field_668ce1275064a',
				'label' => __( 'Limit posts per page', 'partners-site_v2' ),
				'name' => 'limit',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 9,
				'min' => '',
				'max' => '',
				'placeholder' => '',
				'step' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'block',
					'operator' => '==',
					'value'    => 'acf/blog-posts-component',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	));
endif;

