<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_668fd8d66ece8',
			'title'                 => 'Blog Footer',
			'fields'                => array(
				array(
					'key'               => 'field_668fd8d65cf72',
					'label' => __( 'Zdjęcie', 'partners-site_v2' ),
					'name'              => 'img',
					'type'              => 'image',
					'instructions' => __( 'Należy sprawdzić czy wysokość treści nie przewyższa wysokości obrazka<br>(min. szerokość zdjęcia: 944px, Zalecana szerokość: 2832px)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_668fd8f15cf73',
					'label' => __( 'Nagłówek', 'partners-site_v2' ),
					'name'              => 'heading',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_668fd8f35cf74',
					'label' => __( 'Zawartość', 'partners-site_v2' ),
					'name'              => 'content',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'layout_60214709443cz'  => array(
							'key'        => 'layout_60214709443cz',
							'name'       => 'description',
							'label'      => 'Opis',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_668fd8f45cf75',
									'label'             => 'Opis',
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => '',
									'new_lines'         => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_60214709443c1z' => array(
							'key'        => 'layout_60214709443c1z',
							'name'       => 'link',
							'label'      => 'Przycisk',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_668fd8f55cf76',
									'label'             => 'Akcja przycisku',
									'name'              => 'buttonAction',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'link' => 'Link',
										'form' => 'Formularz',
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_668fd8f75cf77',
									'label'             => 'Tekst przycisku',
									'name'              => 'buttonText',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_668fd8f55cf76',
												'operator' => '==',
												'value'    => 'form',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_668fd8f85cf78',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_668fd8f55cf76',
												'operator' => '==',
												'value'    => 'link',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => 'Dodaj zawartość',
					'min'               => '',
					'max'               => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/blog-post-footer',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
