<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6040acb02a4a7',
			'title'                 => __( 'Campaign fields on the slider', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_6040ad670702d',
					'label'				=> __( 'Title', 'partners-site_v2' ),
					'name'              => 'title',
					'type'              => 'text',
					'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 45),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => 45,
				),
				array(
					'key'               => 'field_6040acb907029',
					'label' 			=> __( 'Subtitle', 'partners-site_v2' ),
					'name'              => 'subtitle',
					'type'              => 'text',
					'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 50),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => 50,
				),
				array(
					'key'               => 'field_6040ad240702b',
					'label'             => __( 'Link', 'partners-site_v2' ),
					'name'              => 'link',
					'type'              => 'link',
					'instructions'		=> __( 'If no link is provided, the slide will link to the campaign page', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
				),
				array(
					'key'               => 'field_6040ae150702e',
					'label' 			=> __( 'Photo', 'partners-site_v2' ),
					'name'              => 'image',
					'type'              => 'image',
					'instructions' 		=> __( '(min. width: 1920px, Recommended width: 3840px)<br>(min. height: 807px)<br>The main campaign image used in various sliders on the website.', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 1920,
					'min_height'        => 1080,
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'campaign',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}
