<?php

use Classes\CarDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6103f55455168',
			'title'                 => 'Car Specification',
			'fields'                => array(
				array(
					'key'               => 'field_6103f56d78246',
					'label'             => 'Model',
					'name'              => 'model',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => CarDictionary::getModels(),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_6103f56d78245',
					'label'             => 'Kategoria',
					'name'              => 'category',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => CarDictionary::getModelCategories(),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_6103f57378247',
					'label' => __( 'Prędkość maksymalna (km/h)', 'partners-site_v2' ),
					'name'              => 'max-speed',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6103f58378248',
					'label' => __( 'Pojemność bagażnika (litry)', 'partners-site_v2' ),
					'name'              => 'cargo-capacity',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6103f58b78249',
					'label'             => 'Miejsc',
					'name'              => 'seats',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6103f5917824a',
					'label' => __( 'Wysokość (cm)', 'partners-site_v2' ),
					'name'              => 'height',
					'type'              => 'number',
					'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6103f5977824b',
					'label' => __( 'Długość (cm)', 'partners-site_v2' ),
					'name'              => 'length',
					'type'              => 'number',
					'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6103f5a07824c',
					'label' => __( 'Szerokość z lusterkami (cm)', 'partners-site_v2' ),
					'name'              => 'width',
					'type'              => 'number',
					'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6103f5a87824d',
					'label' => __( 'Prześwit (cm)', 'partners-site_v2' ),
					'name'              => 'ground-clearance',
					'type'              => 'number',
					'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_6110f503d8c8a',
					'label'             => 'Wersje',
					'name'              => 'versions',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'row',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6110f50ed8c8b',
							'label'             => 'Wersja',
							'name'              => 'version',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => CarDictionary::getVersions(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_6110f521d8c8c',
							'label' => __( 'Prędkość maksymalna (km/h)', 'partners-site_v2' ),
							'name'              => 'max-speed',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_6110f52fd8c8d',
							'label' => __( 'Pojemność bagażnika (litry)', 'partners-site_v2' ),
							'name'              => 'cargo-capacity',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_6110f53ed8c8e',
							'label'             => 'Miejsc',
							'name'              => 'seats',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_6110f551d8c8f',
							'label' => __( 'Wysokość (cm)', 'partners-site_v2' ),
							'name'              => 'height',
							'type'              => 'number',
							'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_6110f55cd8c90',
							'label' => __( 'Długość (cm)', 'partners-site_v2' ),
							'name'              => 'length',
							'type'              => 'number',
							'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_6110f562d8c91',
							'label' => __( 'Szerokość z lusterkami (cm)', 'partners-site_v2' ),
							'name'              => 'width',
							'type'              => 'number',
							'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6110f56bd8c92',
							'label' => __( 'Prześwit (cm)', 'partners-site_v2' ),
							'name'              => 'ground-clearance',
							'type'              => 'number',
							'instructions' => __( '<strong>UWAGA! Wartość musi być podana w centymetrach</strong>', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'car-specification',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
