<?php

if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group(
        array(
            'key' => 'group_60586610e9086',
            'title' => 'Ustawienia Dealera',
            'fields' => array(
                array(
                    'key' => 'field_6058b8ba89298',
                    'label' => 'Informacje podstawowe',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0, 
                ),
                array(
                    'key' => 'field_605866451313h',
                    'label' => 'ID dealera',
                    'name' => 'dealerId',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'admin-only' => true,
                ),
                      
                array(
                    'key' => 'field_605866451313d',
                    'label' => 'Nazwa Dealera',
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_605866451313c',
                    'label' => 'Nr telefonu',
                    'name' => 'phone-number',
                    'type' => 'text',
                    'instructions' => __( 'Nr telefonu wyświetlany na dolnej belce strony.', 'partners-site_v2' ),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_605866331313c',
                    'label' => 'Klucz API Google Maps',
                    'name' => 'google-maps-key',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6058j6331313c',
                    'label' => 'ID Google Tag Manager',
                    'name' => 'gtm',
                    'type' => 'text',
                    'instructions' => 'np. "GTM-XXXXX"',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'event_instance',
                    'label' => __( 'ID Instancji eventów', 'partners-site_v2' ),
                    'name' => 'event_instance',
                    'type' => 'text',
                    'instructions' => __( 'Nie wprowadzaj żadnych zmian', 'partners-site_v2' ),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_additional_code',
                    'label' => 'Dodatkowy kod do sekcji head',
                    'name' => 'field_additional_code',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_thankyou_code',
                    'label' => __( 'Dodatkowy kod na podstronie z podziękowaniem', 'partners-site_v2' ),
                    'name' => 'field_thankyou_code',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'code_test_drive',
                    'label' => __( 'Dodatkowy kod na podstronie z podziękowaniem dla jazd testowych', 'partners-site_v2' ),
                    'name' => 'code_test_drive',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'htmlCode',
                    'label' => __( 'Dodatkowy kod html do strony głównej', 'partners-site_v2' ),
                    'name' => 'htmlCode',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'globalJs',
                    'label' => __( 'Dodatkowy kod JavaScript na przycisku pokaż numer telefonu', 'partners-site_v2' ),
                    'name' => 'globalJs',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                  'key'               => 'gSecretKey', 
                  'label'             => 'Klucz GA (Google Analytics)',
                  'name'              => 'gSecretKey',
                  'type'              => 'textarea',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'default_value'     => '',
                  'placeholder'       => '',
                  'maxlength'         => '',
                ),
                array(
                  'key'               => 'gId',
                  'label'             => 'Identyfikator Uslugi (Google Analytics)',
                  'name'              => 'gId',
                  'type'              => 'text',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'default_value'     => '',
                  'placeholder'       => '',
                  'maxlength'         => '',
                ),
                array(
                    'key'               => 'wpPixelKey',
                    'label'             => 'Klucz Wp Pixel',
                    'name'              => 'wpPixelKey',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                      'width' => '',
                      'class' => '',
                      'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'maxlength'         => '',
                  ),
                array(
                    'key' => 'wpPixel',
                    'label' => __( 'skrypt WP PIXEL wł/wył', 'partners-site_v2' ),
                    'name' => 'wpPixel',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),

                array(
                    'key' => 'field_6058b8b089297',
                    'label' => 'Social Media',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_6058b86089290',
                    'label' => 'Social media',
                    'name' => 'social-media',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6058b87189291',
                            'label' => 'Facebook',
                            'name' => 'facebook',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b88989292',
                            'label' => 'Instagram',
                            'name' => 'instagram',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b89389294',
                            'label' => 'Linkedin',
                            'name' => 'linkedin',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b89b89295',
                            'label' => 'YouTube',
                            'name' => 'youtube',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b8a689296',
                            'label' => 'Twitter',
                            'name' => 'twitter',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),

                array(
                    'key' => 'field_6058d2b089297',
                    'label' => 'Integracja YouLead',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_6046b86089290',
                    'label' => 'Integracja YouLead',
                    'name' => 'you-lead',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6058b298189291',
                            'label' => 'Client ID',
                            'name' => 'client-id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b87182691',
                            'label' => 'App ID',
                            'name' => 'app-id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_4158b87189291',
                            'label' => 'App Secret Key',
                            'name' => 'app-secret-key',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_chatter',
                    'label' => 'Integracja Chat',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => true,
                ),
                array(
                    'key' => 'field_chatter_boxes',
                    'label' => 'Integracja Chat',
                    'name' => 'chat-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => true,
                    'sub_fields' => array(
                        array(
                            'key' => 'chat_code',
                            'label' => 'Kod chatu',
                            'name' => 'chat-code',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'chat_status',
                            'label' => __( 'Chat wł/wył', 'partners-site_v2' ),
                            'name' => 'chat_enable',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),

                    ),
                ),
                array(
                    'key' => 'field_webpush',
                    'label' => 'Integracja WEBPUSH',
                    'name' => 'field_webpush',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false
                ),
                array(
                    'key' => 'field_webpushhead',
                    'label' => 'Pliki',
                    'name' => 'field_webpushhead',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_webpush_header',
                            'label' => __( 'Kod do sekcji head (zawartość pliku manifest.json)', 'partners-site_v2' ),
                            'name' => 'field_webpush_header-code',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_webpush_sw',
                            'label' => __( 'Kod sw (zawartośc pliku sw)', 'partners-site_v2' ),
                            'name' => 'field_webpush_sw',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        )

                    ),
                ),
                array(
                    'key' => 'facebook_int',
                    'label' => 'Integracja Facebook',
                    'name' => 'facebook_int',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'facebook_int_settings',
                    'label' => 'Integracja Facebook',
                    'name' => 'facebook_int_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'fb_token',
                            'label' => 'Access Token',
                            'name' => 'fb_token',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'pixel_enable',
                            'label' => __( 'Włącz facebook pixel na każdej podstronie', 'partners-site_v2' ),
                            'name' => 'pixel_enable',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'fb_pixel',
                            'label' => 'Pixel ID',
                            'name' => 'fb_pixel',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_footer_setup',
                    'label' => 'Ustawienia belki dolnej',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_footer_settings',
                    'label' => 'Ustawienia belki',
                    'name' => 'footer-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_homepage',
                            'label' => __( 'Strona główna tekst', 'partners-site_v2' ),
                            'name' => 'homepage_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_homepage_phone',
                            'label' => __( 'Strona główna telefon', 'partners-site_v2' ),
                            'name' => 'field_homepage_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_newcars',
                            'label' => 'Nowe auta tekst',
                            'name' => 'homepage_newcars',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_newcars_phone',
                            'label' => 'Nowe auta telefon',
                            'name' => 'field_newcars_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_usedcars',
                            'label' => __( 'Używane auta tekst', 'partners-site_v2' ),
                            'name' => 'field_usedcars',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_usedcars_phone',
                            'label' => __( 'Używane auta telefon', 'partners-site_v2' ),
                            'name' => 'field_usedcars_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_service',
                            'label' => 'Serwis i akcesoria tekst',
                            'name' => 'service_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_service_phone',
                            'label' => 'Serwis i akcesoria telefon',
                            'name' => 'field_service_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_index_setup',
                    'label' => 'Ustawienia wykluczen indexowania',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_index_settings',
                    'label' => 'Ustawienia wykluczen z indexowania',
                    'name' => 'index-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6672c847750d6',
                            'label' => 'Dokladne adresy url do wykluczenia. Np. https://volvoweb.com/dontIndexMe',
                            'name' => 'items-url',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6672c8ef750d7',
                                    'label' => 'Wyklucz url:',
                                    'name' => 'index-url',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'https://volvoweb.com/dontIndexMe',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6672ccf4129d3',
                            'label' => 'Slowa wystepujace w url do wykluczenia. Np. <b>test</b>, wykluczy takie adresy: <br> - https://volvoweb.com/<b>test</b> <br> - https://volvoweb.com/some/<b>test</b>url',
                            'name' => 'items-word',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6672ccf5129d4',
                                    'label' => 'Slowa wystepujace w url do wykluczenia',
                                    'name' => 'index-word',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'indicata_setup',
                    'label' => __( 'Wyceny pojazdów', 'partners-site_v2' ),
                    'name' => 'indicata_setup',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'indicata_setup_settings',
                    'label' => 'Integracja Indicata',
                    'name' => 'indicata_setup_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'indicata_email',
                            'label' => 'Adres email',
                            'name' => 'indicata_email',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'indicata_address',
                            'label' => __( 'Adres dołączany do wyceny', 'partners-site_v2' ),
                            'name' => 'indicata_address',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),

                    ),
                ),
                array(
                    'key' => 'tab_setup_otomoto',
                    'label' => 'Integracja Otomoto',
                    'name' => 'tab_setup_otomoto',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'otomoto_settings',
                    'label' => 'Integracja Otomoto',
                    'name' => 'otomoto_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'otomoto_enabled',
                            'label' => 'Włącz integrację',
                            'name' => 'otomoto_enabled',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'otomoto_username',
                            'label' => 'Nazwa użytkownika',
                            'name' => 'otomoto_username',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_password',
                            'label' => 'Hasło',
                            'name' => 'otomoto_password',
                            'type' => 'password',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_client_id',
                            'label' => 'Client ID',
                            'name' => 'otomoto_client_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_client_secret',
                            'label' => 'Client Secret',
                            'name' => 'otomoto_client_secret',
                            'type' => 'password',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_test_connection',
                            'label' => 'Test połączenia',
                            'name' => 'otomoto_test_connection',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '<button type="button" class="button" id="otomoto-test-connection">Testuj połączenie</button> <span id="otomoto-connection-status" style="margin-left:10px;"></span>',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'otomoto_region_id',
                            'label' => 'Region',
                            'name' => 'otomoto_region_id',
                            'type' => 'select',
                            'instructions' => 'Wybierz region',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => 'Wybierz region...',
                        ),
                        array(
                            'key' => 'otomoto_city_id',
                            'label' => 'Miasto',
                            'name' => 'otomoto_city_id',
                            'type' => 'select',
                            'instructions' => 'Wybierz miasto',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => 'Wybierz miasto...',
                        ),
                        array(
                            'key' => 'otomoto_district_id',
                            'label' => 'Dzielnica',
                            'name' => 'otomoto_district_id',
                            'type' => 'select',
                            'instructions' => 'Wybierz dzielnicę',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => 'Wybierz dzielnicę...',
                        ),
                        array(
                            'key' => 'otomoto_latitude',
                            'label' => 'Szerokość geograficzna',
                            'name' => 'otomoto_latitude',
                            'type' => 'number',
                            'instructions' => 'Automatycznie uzupełniane po wyborze miasta',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_longitude',
                            'label' => 'Długość geograficzna',
                            'name' => 'otomoto_longitude',
                            'type' => 'number',
                            'instructions' => 'Automatycznie uzupełniana po wyborze miasta',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_contact_person',
                            'label' => 'Osoba kontaktowa',
                            'name' => 'otomoto_contact_person',
                            'type' => 'text',
                            'instructions' => 'Osoba kontaktowa wyświetlana w ogłoszeniu',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'tab_setup_form',
                    'label' => 'Zgody na formularzu',
                    'name' => 'tab_setup_form',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0, 
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),

                array(
                    'key' => 'setup_form_settings',
                    'label' => 'Zgody na formularzu',
                    'name' => 'setup_form_settings',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'iod_email',
                            'label' => 'Adres e-mail Inspektora Ochrony Danych Osobowych',
                            'name' => 'iod_email',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        
                    ),
                ),
                array(
                    'key' => 'tab_booking_engine',
                    'label' => 'Integracja Booking Engine',
                    'name' => 'tab_booking_engine',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'booking_engine_settings',
                    'label' => 'Integracja Booking Engine',
                    'name' => 'booking_engine_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(                       
                        array(
                            'key' => 'ttmsapikey',
                            'label' => 'API Key',
                            'name' => 'ttmsapikey',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'admin-only' => true,
                        ),          
                        array(
                            'key' => 'parmaPartnerCode',
                            'label' => 'Partner Code',
                            'name' => 'parmaPartnerCode',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'admin-only' => true,
                        ),          
                        array(
                            'key' => 'booking_partner_id',
                            'label' => 'Partner ID',
                            'name' => 'partner_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'np. 6PL301',
                        ),
                    ),
                ),

                
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'options-dealer',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        )
    );


endif;
