<?php

if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group(
        array(
            'key' => 'group_60586610e9086',
            'title' => __( 'Dealer settings', 'partners-site_v2' ),
            'fields' => array(
                array(
                    'key' => 'field_6058b8ba89298',
                    'label' => __( 'Basic Information', 'partners-site_v2' ),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0, 
                ),
                array(
                    'key' => 'field_605866451313h',
                    'label' => __( 'Dealer ID', 'partners-site_v2' ),
                    'name' => 'dealerId',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'admin-only' => true,
                ),
                      
                array(
                    'key' => 'field_605866451313d',
                    'label' => __( 'Dealer Name', 'partners-site_v2' ),
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_605866451313c',
                    'label' => __( 'Phone Number', 'partners-site_v2' ),
                    'name' => 'phone-number',
                    'type' => 'text',
                    'instructions' => __( 'Phone number displayed in the footer of the page.', 'partners-site_v2' ),
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_605866331313c',
                    'label' => __( 'Google Maps API Key', 'partners-site_v2' ),
                    'name' => 'google-maps-key',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_6058j6331313c',
                    'label' => __( 'Google Tag Manager ID', 'partners-site_v2' ),
                    'name' => 'gtm',
                    'type' => 'text',
                    'instructions' => __( 'e.g. "GTM-XXXXX"', 'partners-site_v2' ),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'event_instance',
                    'label' => __( 'Event Instance ID', 'partners-site_v2' ),
                    'name' => 'event_instance',
                    'type' => 'text',
                    'instructions' => __( 'Do not make any changes', 'partners-site_v2' ),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_additional_code',
                    'label' => __( 'Additional code for the head section', 'partners-site_v2' ),
                    'name' => 'field_additional_code',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_thankyou_code',
                    'label' => __( 'Additional code for the thank-you page', 'partners-site_v2' ),
                    'name' => 'field_thankyou_code',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'code_test_drive',
                    'label' => __( 'Additional code on the thank-you page for test drives', 'partners-site_v2' ),
                    'name' => 'code_test_drive',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'htmlCode',
                    'label' => __( 'Additional HTML code for the homepage', 'partners-site_v2' ),
                    'name' => 'htmlCode',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'globalJs',
                    'label' => __( 'Additional JavaScript code for the "Show Phone Number" button', 'partners-site_v2' ),
                    'name' => 'globalJs',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                  'key'               => 'gSecretKey', 
                  'label'             => __( 'GA (Google Analytics) Key', 'partners-site_v2' ),
                  'name'              => 'gSecretKey',
                  'type'              => 'textarea',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'default_value'     => '',
                  'placeholder'       => '',
                  'maxlength'         => '',
                ),
                array(
                  'key'               => 'gId',
                  'label'             => __( 'Service ID (Google Analytics)', 'partners-site_v2' ),
                  'name'              => 'gId',
                  'type'              => 'text',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                  ),
                  'default_value'     => '',
                  'placeholder'       => '',
                  'maxlength'         => '',
                ),
                array(
                    'key'               => 'wpPixelKey',
                    'label'             => __( 'WP Pixel Key', 'partners-site_v2' ),
                    'name'              => 'wpPixelKey',
                    'type'              => 'text',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                      'width' => '',
                      'class' => '',
                      'id'    => '',
                    ),
                    'default_value'     => '',
                    'placeholder'       => '',
                    'maxlength'         => '',
                  ),
                array(
                    'key' => 'wpPixel',
                    'label' => __( 'WP PIXEL script on/off', 'partners-site_v2' ),
                    'name' => 'wpPixel',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                ),

                array(
                    'key' => 'field_6058b8b089297',
                    'label' => __('Social Media', 'partners-site_v2'),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_6058b86089290',
                    'label' => __('Social Media', 'partners-site_v2'),
                    'name' => 'social-media',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6058b87189291',
                            'label' => __('Facebook', 'partners-site_v2'),
                            'name' => 'facebook',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b88989292',
                            'label' => __('Instagram', 'partners-site_v2'),
                            'name' => 'instagram',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b89389294',
                            'label' => __( 'LinkedIn', 'partners-site_v2' ),
                            'name' => 'linkedin',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b89b89295',
                            'label' => __('YouTube', 'partners-site_v2'),
                            'name' => 'youtube',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b8a689296',
                            'label' => __( 'Twitter', 'partners-site_v2' ),
                            'name' => 'twitter',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),

                array(
                    'key' => 'field_6058d2b089297',
                    'label' => __( 'Integration YouLead', 'partners-site_v2' ),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_6046b86089290',
                    'label' => __( 'Integration YouLead', 'partners-site_v2' ),
                    'name' => 'you-lead',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6058b298189291',
                            'label' => __('Client ID', 'partners-site_v2'),
                            'name' => 'client-id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_6058b87182691',
                            'label' => __('App ID', 'partners-site_v2'),
                            'name' => 'app-id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_4158b87189291',
                            'label' => __('App Secret Key', 'partners-site_v2'),
                            'name' => 'app-secret-key',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_chatter',
                    'label' => __( 'Chat Integration', 'partners-site_v2' ),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => true,
                ),
                array(
                    'key' => 'field_chatter_boxes',
                    'label' => __( 'Chat Integration', 'partners-site_v2' ),
                    'name' => 'chat-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => true,
                    'sub_fields' => array(
                        array(
                            'key' => 'chat_code',
                            'label' => __( 'Chat code', 'partners-site_v2' ),
                            'name' => 'chat-code',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'chat_status',
                            'label' => __( 'Chat on/off', 'partners-site_v2' ),
                            'name' => 'chat_enable',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),

                    ),
                ),
                array(
                    'key' => 'field_webpush',
                    'label' => __( 'WEBPUSH Integration', 'partners-site_v2' ),
                    'name' => 'field_webpush',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false
                ),
                array(
                    'key' => 'field_webpushhead',
                    'label' => __( 'Files', 'partners-site_v2' ),
                    'name' => 'field_webpushhead',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_webpush_header',
                            'label' => __( 'Code for the head section (contents of the manifest.json file)', 'partners-site_v2' ),
                            'name' => 'field_webpush_header-code',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_webpush_sw',
                            'label' => __( 'SW Code (contents of the sw file)', 'partners-site_v2' ),
                            'name' => 'field_webpush_sw',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        )

                    ),
                ),
                array(
                    'key' => 'facebook_int',
                    'label' => __( 'Facebook Integration', 'partners-site_v2' ),
                    'name' => 'facebook_int',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'facebook_int_settings',
                    'label' => __( 'Facebook Integration', 'partners-site_v2' ),
                    'name' => 'facebook_int_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'fb_token',
                            'label' => __('Access Token', 'partners-site_v2'),
                            'name' => 'fb_token',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'pixel_enable',
                            'label' => __( 'Enable Facebook Pixel on every subpage', 'partners-site_v2' ),
                            'name' => 'pixel_enable',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'fb_pixel',
                            'label' => __('Pixel ID', 'partners-site_v2'),
                            'name' => 'fb_pixel',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_footer_setup',
                    'label' => __( 'Bottom Bar Settings', 'partners-site_v2' ),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_footer_settings',
                    'label' => __( 'Bar Settings', 'partners-site_v2' ),
                    'name' => 'footer-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_homepage',
                            'label' => __( 'Homepage Text', 'partners-site_v2' ),
                            'name' => 'homepage_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_homepage_phone',
                            'label' => __( 'Homepage Phone', 'partners-site_v2' ),
                            'name' => 'field_homepage_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_newcars',
                            'label' => __( 'New Cars Text', 'partners-site_v2' ),
                            'name' => 'homepage_newcars',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_newcars_phone',
                            'label' => __( 'New Cars Phone', 'partners-site_v2' ),
                            'name' => 'field_newcars_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_usedcars',
                            'label' => __( 'Used Cars Text', 'partners-site_v2' ),
                            'name' => 'field_usedcars',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_usedcars_phone',
                            'label' => __( 'Used Cars Phone', 'partners-site_v2' ),
                            'name' => 'field_usedcars_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_service',
                            'label' => __( 'Service and Accessories Text', 'partners-site_v2' ),
                            'name' => 'service_text',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_service_phone',
                            'label' => __( 'Service and Accessories Phone', 'partners-site_v2' ),
                            'name' => 'field_service_phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_index_setup',
                    'label' => __( 'Indexing Exclusion Settings', 'partners-site_v2' ),
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'field_index_settings',
                    'label' => __( 'Indexing Exclusion Settings', 'partners-site_v2' ),
                    'name' => 'index-group',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6672c847750d6',
                            'label' => __( 'Exact URLs to exclude. E.g. https://volvoweb.com/dontIndexMe', 'partners-site_v2' ),
                            'name' => 'items-url',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6672c8ef750d7',
                                    'label' => __( 'Exclude URL:', 'partners-site_v2' ),
                                    'name' => 'index-url',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => 'https://volvoweb.com/dontIndexMe',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6672ccf4129d3',
                            'label' => __( 'Words appearing in the URL to exclude.', 'partners-site_v2' ),
                            'name' => 'items-word',
                            'type' => 'repeater',
                            'instructions' => __( 'E.g. <b>test</b>, will exclude such addresses:<br> - https://volvoweb.com/<b>test</b> <br> - https://volvoweb.com/some/<b>test</b>url', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6672ccf5129d4',
                                    'label' => __( 'Words appearing in URLs to exclude', 'partners-site_v2' ),
                                    'name' => 'index-word',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                            ),
                        ),
                    ),
                ),
                array(
                    'key' => 'indicata_setup',
                    'label' => __( 'Vehicle Quotes', 'partners-site_v2' ),
                    'name' => 'indicata_setup',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'admin-only' => false,
                ),
                array(
                    'key' => 'indicata_setup_settings',
                    'label' => __( 'Indicat Integration', 'partners-site_v2' ),
                    'name' => 'indicata_setup_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'indicata_email',
                            'label' => __( 'Email Address', 'partners-site_v2' ),
                            'name' => 'indicata_email',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'indicata_address',
                            'label' => __( 'Address included in the offer', 'partners-site_v2' ),
                            'name' => 'indicata_address',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),

                    ),
                ),
                array(
                    'key' => 'tab_setup_otomoto',
                    'label' => __( 'Otomoto Integration', 'partners-site_v2' ),
                    'name' => 'tab_setup_otomoto',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'otomoto_settings',
                    'label' => __( 'Otomoto Integration', 'partners-site_v2' ),
                    'name' => 'otomoto_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'admin-only' => false,
                    'sub_fields' => array(
                        array(
                            'key' => 'otomoto_enabled',
                            'label' => __( 'Enable integration', 'partners-site_v2' ),
                            'name' => 'otomoto_enabled',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        array(
                            'key' => 'otomoto_username',
                            'label' => __( 'Username', 'partners-site_v2' ),
                            'name' => 'otomoto_username',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_password',
                            'label' => __( 'Password', 'partners-site_v2' ),
                            'name' => 'otomoto_password',
                            'type' => 'password',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_client_id',
                            'label' => __('Client ID', 'partners-site_v2'),
                            'name' => 'otomoto_client_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_client_secret',
                            'label' => __('Client Secret', 'partners-site_v2'),
                            'name' => 'otomoto_client_secret',
                            'type' => 'password',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_test_connection',
                            'label' => __( 'Connection test', 'partners-site_v2' ),
                            'name' => 'otomoto_test_connection',
                            'type' => 'message',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '<button type="button" class="button" id="otomoto-test-connection">' . __( 'Test connection', 'partners-site_v2' ) . '</button> <span id="otomoto-connection-status" style="margin-left:10px;"></span>',
                            'new_lines' => 'wpautop',
                            'esc_html' => 0,
                        ),
                        array(
                            'key' => 'otomoto_region_id',
                            'label' => __('Region', 'partners-site_v2'),
                            'name' => 'otomoto_region_id',
                            'type' => 'select',
                            'instructions' => __( 'Select region', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => __( 'Select region...', 'partners-site_v2' ),
                        ),
                        array(
                            'key' => 'otomoto_city_id',
                            'label' => __( 'City', 'partners-site_v2' ),
                            'name' => 'otomoto_city_id',
                            'type' => 'select',
                            'instructions' => __( 'Select city', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => __( 'Select city...', 'partners-site_v2' ),
                        ),
                        array(
                            'key' => 'otomoto_district_id',
                            'label' => __( 'District', 'partners-site_v2' ),
                            'name' => 'otomoto_district_id',
                            'type' => 'select',
                            'instructions' => __( 'Select district', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'choices' => array(),
                            'default_value' => '',
                            'allow_null' => 1,
                            'placeholder' => __( 'Select district...', 'partners-site_v2' ),
                        ),
                        array(
                            'key' => 'otomoto_latitude',
                            'label' => __( 'Latitude', 'partners-site_v2' ),
                            'name' => 'otomoto_latitude',
                            'type' => 'number',
                            'instructions' => __( 'Automatically filled in after selecting a city', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_longitude',
                            'label' => __( 'Longitude', 'partners-site_v2' ),
                            'name' => 'otomoto_longitude',
                            'type' => 'number',
                            'instructions' => __( 'Automatically filled in after selecting a city', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '50',
                                'class' => 'otomoto-location-field',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'otomoto_contact_person',
                            'label' => __( 'Contact person', 'partners-site_v2' ),
                            'name' => 'otomoto_contact_person',
                            'type' => 'text',
                            'instructions' => __( 'Contact person displayed in the listing', 'partners-site_v2' ),
                            'required' => 0,
                            'conditional_logic' => array(
                                array(
                                    array(
                                        'field' => 'otomoto_enabled',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'tab_setup_form',
                    'label' => __( 'Consents on the form', 'partners-site_v2' ),
                    'name' => 'tab_setup_form',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0, 
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),

                array(
                    'key' => 'setup_form_settings',
                    'label' => __( 'Consents on the form', 'partners-site_v2' ),
                    'name' => 'setup_form_settings',
                    'type' => 'group',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'iod_email',
                            'label' => __( 'Email address of the Data Protection Officer', 'partners-site_v2' ),
                            'name' => 'iod_email',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        
                    ),
                ),
                array(
                    'key' => 'tab_booking_engine',
                    'label' => __( 'Booking Engine integration', 'partners-site_v2' ),
                    'name' => 'tab_booking_engine',
                    'type' => 'tab',
                    'placement' => 'top',
                    'endpoint' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'booking_engine_settings',
                    'label' => __( 'Booking Engine integration', 'partners-site_v2' ),
                    'name' => 'booking_engine_settings',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(                       
                        array(
                            'key' => 'ttmsapikey',
                            'label' => __('API Key', 'partners-site_v2'),
                            'name' => 'ttmsapikey',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'admin-only' => true,
                        ),          
                        array(
                            'key' => 'parmaPartnerCode',
                            'label' => __('Partner Code', 'partners-site_v2'),
                            'name' => 'parmaPartnerCode',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'admin-only' => true,
                        ),          
                        array(
                            'key' => 'booking_partner_id',
                            'label' => __('Partner ID', 'partners-site_v2'),
                            'name' => 'partner_id',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => __( 'e.g. 6PL301', 'partners-site_v2' ),
                        ),
                    ),
                ),

                
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'options-dealer',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        )
    );


endif;
