<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6050d3cf430c2',
			'title'                 => __( 'Employee', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_6050d3d92bb33',
					'label' 			=> __( 'First Name', 'partners-site_v2' ),
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6050d3ea2bb34',
					'label'             => __( 'Last Name', 'partners-site_v2' ),
					'name'              => 'surname',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6050d3f32bb35',
					'label'             => __( 'Position', 'partners-site_v2' ),
					'name'              => 'position',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6050d3fa2bb36',
					'label'             => __( 'Phone Number', 'partners-site_v2' ),
					'name'              => 'phone',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6050d4052bb37',
					'label'             => __( 'Email Address', 'partners-site_v2' ),
					'name'              => 'email',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6050d4132bb38',
					'label' 			=> __( 'Department', 'partners-site_v2' ),
					'name'              => 'category',
					'type'              => 'network_taxonomy',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'taxonomy'          => 'employee_category',
					'field_type'        => 'select',
					'allow_null'        => 0,
					'add_term'          => 0,
					'save_terms'        => 0,
					'load_terms'        => 0,
					'return_format'     => 'id',
					'multiple'          => 0,
				),
				array(
					'key'                             => 'field_6050d42b2bb39',
					'label'                           => __( 'Showroom', 'partners-site_v2' ),
					'name'                            => 'showroom',
					'type'                            => 'post_object',
					'instructions'                    => '',
					'required'                        => 1,
					'conditional_logic'               => 0,
					'wrapper'                         => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'                       => array(
						0 => 'showroom',
					),
					'taxonomy'                        => '',
					'allow_null'                      => 0,
					'multiple'                        => 0,
					'return_format'                   => 'id',
					'ui'                              => 1,
					'multi-showroom-and-service-only' => true,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'employee',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'discussion',
				4  => 'comments',
				5  => 'slug',
				6  => 'author',
				7  => 'format',
				8  => 'page_attributes',
				9  => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
			'active'                => true,
			'description'           => '',
		)
	);
endif;
