<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6076ac56e6af1',
			'title'                 => 'Opcje formularza',
			'fields'                => array(
				array(
					'key'               => 'field_6076ac63aafd1',
					'label'             => 'Pole source',
					'name'              => 'source',
					'type'              => 'text',
					'instructions' => __( 'Pole source wysyłane do systemu DOL', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'one_page',
					'label' => __( 'Wyświetlaj kampanię jako landing page', 'partners-site_v2' ),
					'name'              => 'one_page',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => 'Nie',
						'on' => 'Tak'
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'side_form',
					'label'             => 'Formularz po prawej stronie',
					'name'              => 'side_form',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => 'Nie',
						'on' => 'Tak'
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'double_opt',
					'label' => __( 'Włącz dla formularza double opt-in', 'partners-site_v2' ),
					'name'              => 'double_opt',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50%',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => 'Nie',
						'on' => 'Tak'
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key' => 'disable_choose_cat',
					'label' => __( 'Wymusić jedną kategorię tego formularza?', 'partners-site_v2' ),
					'name' => 'disable_choose_cat',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50%',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key'               => 'field_6062dsa3bd29',
					'label'             => 'Cel formularza',
					'name'              => 'destination',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'allvalues' => 'Użytkownik może wybrać',
						'new-cars'  => 'Auta nowe',
						'used-cars' => 'Auta używane',
						'service'   => 'Serwis'
						
					),
					'default_value'     => 'allvalues',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_thankyou_code_js',
					'label' => __( 'Dodatkowy kod javascript na podstronie z podziękowaniem', 'partners-site_v2' ),
					'name'              => 'field_thankyou_code_js',
					'type'              => 'textarea',
					'instructions'      => 'Dynamiczna zmienna ||time||',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_thankyou_code',
					'label' => __( 'Dodatkowy kod html podstronie z podziękowaniem', 'partners-site_v2' ),
					'name'              => 'field_thankyou_code',
					'type'              => 'textarea',
					'instructions'      => 'Dynamiczna zmienna ||time||',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'globalHtml',
					'label'             => 'Dodatkowy kod na podstronie',
					'name'              => 'globalHtml',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'page',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'stock-car',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'campaign',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'parent',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
