<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6076ac56e6af1',
			'title'                 => __( 'Form options', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_6076ac63aafd1',
					'label'             => __( 'Source field', 'partners-site_v2' ),
					'name'              => 'source',
					'type'              => 'text',
					'instructions' 		=> __( 'Source field sent to the DOL system', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'one_page',
					'label' 			=> __( 'Display the campaign as a landing page', 'partners-site_v2' ),
					'name'              => 'one_page',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => __( 'No', 'partners-site_v2' ),
						'on' => __( 'Yes', 'partners-site_v2' )
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'side_form',
					'label'             => __( 'Form on the right', 'partners-site_v2' ),
					'name'              => 'side_form',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => __( 'No', 'partners-site_v2' ),
						'on' => __( 'Yes', 'partners-site_v2' )
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'double_opt',
					'label' 			=> __( 'Turn on double opt-in in the form', 'partners-site_v2' ),
					'name'              => 'double_opt',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50%',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'   => __( 'No', 'partners-site_v2' ),
						'on' 	=> __( 'Yes', 'partners-site_v2' )
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key' => 'disable_choose_cat',
					'label' => __( 'Force a single category for this form?', 'partners-site_v2' ),
					'name' => 'disable_choose_cat',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50%',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key'               => 'field_6062dsa3bd29',
					'label'             => __( 'Form goal', 'partners-site_v2' ),
					'name'              => 'destination',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'allvalues' => __( 'The user can select', 'partners-site_v2' ),
						'new-cars'  => __( 'New cars', 'partners-site_v2' ),
						'used-cars' => __( 'Used cars', 'partners-site_v2' ),
						'service'   => __( 'Service', 'partners-site_v2' )
						
					),
					'default_value'     => 'allvalues',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_thankyou_code_js',
					'label' 			=> __( 'Additional JavaScript code on the thank-you page', 'partners-site_v2' ),
					'name'              => 'field_thankyou_code_js',
					'type'              => 'textarea',
					'instructions'      => __( 'Dynamic variable ||time||', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_thankyou_code',
					'label' 			=> __( 'Additional HTML code on the thank-you page', 'partners-site_v2' ),
					'name'              => 'field_thankyou_code',
					'type'              => 'textarea',
					'instructions'      => __( 'Dynamic variable ||time||', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'globalHtml',
					'label'             => __( 'Additional code on the page', 'partners-site_v2' ),
					'name'              => 'globalHtml',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
			'location'             => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'page',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'stock-car',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'campaign',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'parent',
					),
				),
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
				),
			),
			'menu_order'            => 1,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
