<?php

use Classes\IconsDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6040abef6f8e7',
			'title'                 => __( 'Homepage Option Fields', 'partners-site_v2' ),
			'fields'                => array( 
				// Główny Slider
				array(
					'key'               => 'field_6040ae9e41086',
					'label' => __( 'Main Slider', 'partners-site_v2' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'field_6040b1f2a66b3',
					'label' => __( 'Main Slider', 'partners-site_v2' ),
					'name'              => 'slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040aed641087',
							'label' => __( 'Campaigns displayed in the slider', 'partners-site_v2' ),
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => __( '(up to 3 campaigns)', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => __('Add a campaign', 'partners-site_v2'),
							'sub_fields'        => array(
								
								array(
									'key'               => 'field_605f5e7850fbe',
									'label'             => __('Campaign type', 'partners-site_v2'),
									'name'              => 'type',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'local'  => __('Local campaign', 'partners-site_v2'),
										'global' => __('Global campaign', 'partners-site_v2'),
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_605f5ea150fbf',
									'label'             => __( 'Campaign', 'partners-site_v2' ),
									'name'              => 'local-campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_605f5e7850fbe',
												'operator' => '==',
												'value'    => 'local',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key'               => 'field_605f5ec150fc0',
									'label'             => __( 'Campaign', 'partners-site_v2' ),
									'name'              => 'global-campaign',
									'type'              => 'network_post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_605f5e7850fbe',
												'operator' => '==',
												'value'    => 'global',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key' => 'hide_campaign',
									'label' => __('Replace campaigns', 'partners-site_v2'),
									'name' => 'hide_campaign',
									'type' => 'network_post_object',
									'instructions' => '',
									'required' => 0, 
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_605f5e7850fbe',
												'operator' => '==',
												'value' => 'global',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
										0 => 'campaign',
									),
									'taxonomy' => '',
									'allow_null' => 0,
									'multiple' => 0,
									'admin-only' => false,
									'return_format' => 'id',
									'ui' => 1,
								),
								array(
									'key' => 'force_campaign',
									'label' => __('Force this campaign?', 'partners-site_v2'),
									'name' => 'force_campaign',
									'type' => 'true_false',
									'instructions' => __( 'Selecting this option will enforce this campaign across all instances.', 'partners-site_v2' ),
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_605f5e7850fbe', 
												'operator' => '==',
												'value' => 'global',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => 'Tak',
									'ui_off_text' => 'Nie',
								),
							),
						),
					),
				),

				// Oferta specjalna
				array(
					'key'               => 'specialOffer',
					'label'             => __('Special offer', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'onOffOffer',
					'label' => __('Should this offer be displayed?', 'partners-site_v2'),
					'name'              => 'offerBtn',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'specialOfferTitle',
					'label'             => __( 'Description', 'partners-site_v2' ),
					'name'              => 'offerTitle',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),
				array(
					'key'               => 'offerLinks',
					'label'             => __( 'Link', 'partners-site_v2' ),
					'name'              => 'offerLinks',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '60',
				),
				

				
				


				// szare boksy 
				array(
					'key'               => 'greyBox',
					'label'             => __('Gray boxes', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'global_content_checkbox',
					'label' => __('Should global content be loaded?', 'partners-site_v2'),
					'name'              => 'global_content_checkbox',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'default_value'     => 1,  
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'ui'                => 1,  
					'ui_on_text'        => 'Tak',
					'ui_off_text'       => 'Nie',
				),
				

				array(
					'key'               => 'greyBox1',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 1),
					'name'              => 'greyBox1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox2',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 2),
					'name'              => 'greyBox2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle2',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription2',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox2',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox3',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 3),
					'name'              => 'greyBox3',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle3',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription3',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox3',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link3',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox4',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 4),
					'name'              => 'greyBox4',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,  
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle4',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading4',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription4',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description4',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox4',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link4',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				

				// Sprzedaż
				array(
					'key'               => 'field_6040b1d2a66b2',
					'label' => __('Sales', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
					'admin-only' => true,
				),
				array(
					'key'               => 'field_6040b0e9a66af',
					'label' => __('Sales', 'partners-site_v2'),
					'name'              => 'offers',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'admin-only'        => true,
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040b0fca66b0',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' => __( 'By default, the header text is gray. To make a specific phrase black, please place it between &lt;strong&gt;&lt;/strong&gt;, <br>e.g., &lt;strong&gt;TEXT&lt;/strong&gt;', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'child-site-only'   => false,
						),
						array(
							'key'               => 'field_6042225721aa6',
							'label' => __('Enable Preview Component', 'partners-site_v2'),
							'name'              => 'enable-preview-component',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 1,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_6040b24ea66b4',
							'label'             => __('Preview Component', 'partners-site_v2'),
							'name'              => 'preview-component',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6042225721aa6',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'child-site-only'   => false,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b3a6a66b5',
									'label' => __( 'Photo', 'partners-site_v2' ),
									'name'              => 'image',
									'type'              => 'image',
									'instructions' => __('(min. width: 944px, Recommended width: 2832px)', 'partners-site_v2'),
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'integer',
									'preview_size'      => 'medium',
									'library'           => 'all',
									'min_width'         => 612,
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								
								array(
									'key'               => 'field_6040b40ba66b7',
									'label' => __( 'Header', 'partners-site_v2' ),
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_6040b41ba66b8',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => '',
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_6040b435a66b9',
									'label'             => __( 'Link', 'partners-site_v2' ),
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
						),
						array(
							'key'               => 'field_6040b4b5a66ba',
							'label' => __('Sales blocks', 'partners-site_v2'),
							'name'              => 'offer-boxes',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'admin-only'        => false,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b4cea66bb',
									'label'             => __('Elements', 'partners-site_v2'),
									'name'              => 'items',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 3,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6040b4f3a66bc',
											'label'        => __('Icon', 'partners-site_v2'),
											'name'         => 'icon',
											'type'         => 'icon_select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => IconsDictionary::getIcons(),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'value',
											'ui'           => 1,
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_6040b51ca66bd',
											'label' => __( 'Header', 'partners-site_v2' ),
											'name'         => 'heading',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_6040b523a66be',
											'label'        => __( 'Description', 'partners-site_v2' ),
											'name'         => 'description',
											'type'         => 'textarea',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'maxlength'    => '',
											'rows'         => '',
											'new_lines'    => '',
										),
										array(
											'key'          => 'field_6040b53ea66bf',
											'label'        => __( 'Link', 'partners-site_v2' ),
											'name'         => 'link',
											'type'         => 'link',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'return_format' => 'array',
										),
									),
								),
							),
						),
					),
				),
				// oferta 2 karty
				array(
					'key'               => 'offerTwoCards',
					'label'             => __('Two-card listing', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'offerFirstCard',
					'label'             => sprintf(__( 'Offer card %s', 'partners-site_v2' ), 1),
					'name'              => 'offer1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageCard',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageCard',
							'type'              => 'image',
							'instructions' => __('Add a photo for the card.', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						

						array(
							'key'               => 'choiceInput',
							'label' => __('Select an option', 'partners-site_v2'),
							'name'              => 'select_option',
							'type'              => 'select',
							'instructions' => __('Select one of the available options.', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'gwarancja'    => __( 'Warranty', 'partners-site_v2' ),
								'bezpieczenstwo' => __( 'Safety', 'partners-site_v2' ),
								'akcesoria' => __( 'Accessories', 'partners-site_v2' ),
								'oferta'	=> __( 'Offer', 'partners-site_v2' ),
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
						

						array(
							'key'               => 'titleCard',
							'label' => __('Card title', 'partners-site_v2'),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionCard',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'descriptionCard',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksCard',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerSecondCard',
					'label'             => sprintf(__( 'Offer card %s', 'partners-site_v2' ), 2),
					'name'              => 'offer2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageCard2',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageCard2',
							'type'              => 'image',
							'instructions' => __('Add a photo for the card.', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						

						array(
							'key'               => 'choiceInput2',
							'label' => __('Select an option', 'partners-site_v2'),
							'name'              => 'select_option2',
							'type'              => 'select',
							'instructions' => __('Select one of the available options.', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'gwarancja'    => __( 'Warranty', 'partners-site_v2' ),
								'bezpieczenstwo' => __( 'Safety', 'partners-site_v2' ),
								'akcesoria' => __( 'Accessories', 'partners-site_v2' ),
								'oferta'	=> __( 'Offer', 'partners-site_v2' ),
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
						

						array(
							'key'               => 'titleCard2',
							'label' => __('Card title', 'partners-site_v2'),
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionCard2',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'descriptionCard2',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
							'new_lines'         => '',
						),
						array(
							'key'               => 'linksCard2',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),

				// slider Rodzina
				array(
					'key'               => 'sliderFamily',
					'label'             => __('Volvo family', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array( 
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'sliderTitle',
					'label' => __( 'Header', 'partners-site_v2' ),
					'name'              => 'sliderTitle',
					'type'              => 'text',
					'instructions' => __('To make the text gray, place it between &lt;strong&gt;&lt;/strong&gt; tags', 'partners-site_v2'),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),
				array(
					'key'               => 'sliderFamilyBox',
					'label'             => __('Slider Family Volvo', 'partners-site_v2'),
					'name'              => 'sliderFamilyBox',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'choiceFamily',
							'label' => __('Select an option', 'partners-site_v2'),
							'name'              => 'choiceFamily',
							'type'              => 'select',
							'instructions' => __('Select one of the available options.', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'suv'    => __( 'SUV', 'partners-site_v2' ),
								'sedan' => __( 'Sedan', 'partners-site_v2' ),
								'kombi'    => __( 'Station wagon', 'partners-site_v2' ),
								'electric' => __( 'Electric_', 'partners-site_v2' ),
							
		
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'label',
							'placeholder'       => '',
						),

						array(
							'key'               => 'imageslider',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageSlider',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
					
						array(
							'key'               => 'nameCar',
							'label'             => __('Model Volvo', 'partners-site_v2'),
							'name'              => 'nameCar',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'priceCar',
							'label'             => __('Car price', 'partners-site_v2'),
							'name'              => 'priceCar',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksSlide',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'linksSlide',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				
				// oferta 3 boksy
				array(
					'key'               => 'offerThreeBox',
					'label'             => __('Three-box offer', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),

				array(
					'key'               => 'mainTitleBox',
					'label'             => __( 'Header', 'partners-site_v2' ),
					'name'              => 'mainHeading',
					'type'              => 'text',
					'instructions' => __('By default, the text is dark; if any part is to be highlighted in gray, surround it with &lt;strong&gt;&lt;/strong&gt; tags', 'partners-site_v2'),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),

				array(
					'key'               => 'offerThreeBox1',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 1),
					'name'              => 'offerBox1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageBox',
							'type'              => 'image',
							'instructions' => __('Add photo', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox2',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 2),
					'name'              => 'offerBox2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox2',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageBox2',
							'type'              => 'image',
							'instructions' => __('Add photo', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox2',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox2',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description2',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox2',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox3',
					'label'             => sprintf(__('Box %s', 'partners-site_v2'), 3),
					'name'              => 'offerBox3',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox3',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'imageBox3',
							'type'              => 'image',
							'instructions' => __('Add photo', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox3',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox3',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description3',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox3',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link3',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				

				//  Oferta
				array(
					'key'               => 'offerCardTab',
					'label'             => __('Offer', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'OfferCard',
					'label'             => __('Offer', 'partners-site_v2'),
					'name'              => 'OfferCard',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'admin-only'        => false,
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'imageOffer',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format' => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'headingOffer',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'headingOffer',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'child-site-only'   => false,
						),
						array(
							'key'               => 'descriptionOffer',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'linkOffer',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
					),
				),

				// Dostępne na miejscu
				array(
					'key'               => 'field_6040b56fa66c0',
					'label' => __('Available on site', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => true,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'field_6040b579a66c1',
					'label' => __('Available on site', 'partners-site_v2'),
					'name'              => 'stock-cars',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040b58aa66c2',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' => __( 'By default, the header text is gray. To make a specific phrase black, please place it between &lt;strong&gt;&lt;/strong&gt;, <br>e.g., &lt;strong&gt;TEXT&lt;/strong&gt;', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'field_6040b479a66c1',
							'label'             => __('Teaser', 'partners-site_v2'),
							'name'              => 'excerpt',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b58aa66c3',
									'label' => __( 'Header', 'partners-site_v2' ),
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_6040b58aa66c4',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 100,
								),
								array(
									'key'               => 'field_6040b435a66a0',
									'label'             => __( 'Link', 'partners-site_v2' ),
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
						),
					),
				),
				// Zdjęcie na dole strony głównej
				array(
					'key'               => 'field_6040b5b9a66c4',
					'label' => __('Photo at the bottom of the homepage', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => true,
					'endpoint'          => 0,
					'child-site-only'   => false,
					'admin-only' => true,
				),
				array(
					'key'               => 'mobile_homepage_image',
					'label' => __('Mobile photo', 'partners-site_v2'),
					'name'              => 'mobile_homepage_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 612,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'admin-only' => true,
				),
				array(
					'key'               => 'field_6040b5d5a66c5',
					'label' => __('Photo at the bottom of the homepage', 'partners-site_v2'),
					'name'              => 'bottom-image',
					'type'              => 'image',
					'instructions' => __('(min. width: 1920px, Recommended width: 3840px)', 'partners-site_v2'),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'admin-only'        => true,
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 1280,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'child-site-only'   => false,
				),
				array(
					'key'               => 'mobile_homepage_image',
					'label' => __('Mobile photo', 'partners-site_v2'),
					'name'              => 'mobile_homepage_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 612,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'options-homepage',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}

add_filter( 'acf/fields/relationship/query/key=field_6040aed641087', 'modifyHomepageSliderItemsQuery', 10, 3 );
function modifyHomepageSliderItemsQuery( $args, $field, $post_id ): array {
	$args['network']   = true;
	$args['sites__in'] = array( 1, get_current_blog_id() );
	return $args;
}

add_filter( 'acf/fields/relationship/result', 'modifyHomepageSliderItemsResult', 10, 4 );
function modifyHomepageSliderItemsResult( $text, $post ): string {
	if ( get_current_blog_id() !== 1 && $post->site_ID == 1 ) {
		return '[Globalna] ' . $text;
	}
	return $text;
}
