<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

	switch_to_blog( 1 );
	$formOptions = get_field( 'form', 'options-service' );
	$models      = array();
	foreach ( $formOptions['models'] as $model ) {
		$models[ $model['name'] ] = $model['name'];
	}

	$services = array();
	foreach ( $formOptions['services'] as $service ) {
		$services[ $service['name'] ] = $service['name'];
	}
	restore_current_blog();

	acf_add_local_field_group(
		array(
			'key'                   => 'group_602ce7ed1f9a5',
			'title'                 => 'Lead\'s fields',
			'fields'                => array(
				array(
					'key'                             => 'field_6050d42b2bb49',
					'label'                           => 'Salon',
					'name'                            => 'showroom',
					'type'                            => 'post_object',
					'instructions'                    => '',
					'required'                        => 1,
					'conditional_logic'               => 0,
					'wrapper'                         => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'                       => array(
						0 => 'showroom',
					),
					'taxonomy'                        => '',
					'allow_null'                      => 0,
					'multiple'                        => 0,
					'return_format'                   => 'id',
					'ui'                              => 1,
					'multi-showroom-and-service-only' => true,
				),
				array(
					'key'               => 'field_602ce98031382',
					'label'             => 'Adres pochodzenia leada',
					'name'              => 'originUrl',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_602ce83b313d2',
					'label'             => 'source',
					'name'              => 'source',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602cec5131383',
					'label' => __( 'Źródło formularza', 'partners-site_v2' ),
					'name'              => 'origin',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'default'    => 'Domyślne',
						'used-cars'  => 'Samochody używane',
						'service'    => 'Serwis',
						'test-drive' => 'Jazda Testowa',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602cec5131384',
					'label'             => 'Cel formularza',
					'name'              => 'destination',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'new-cars'  => 'Auta nowe',
						'used-cars' => 'Auta używane',
						'service'   => 'Serwis',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602cec6b31384',
					'label'             => 'Status',
					'name'              => 'status',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'sent'  => 'Sent',
						'saved' => 'Saved',
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_602ce8213137a',
					'label' => __( 'Imię', 'partners-site_v2' ),
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602ce83b3137b',
					'label'             => 'Nazwisko',
					'name'              => 'surname',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602ce8743137c',
					'label'             => 'Numer telefonu',
					'name'              => 'phoneNumber',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602ce8ac3137d',
					'label'             => 'E-mail',
					'name'              => 'email',
					'type'              => 'email',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
				array(
					'key'               => 'field_612ce98031382',
					'label'             => 'referrer',
					'name'              => 'referrer',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_602ce8bb3137e',
					'label' => __( 'Wiadomość', 'partners-site_v2' ),
					'name'              => 'message',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_612cedas9da31382',
					'label'             => 'VIN',
					'name'              => 'vin',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'service',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_612ce912da31382',
					'label'             => 'Rok produkcji',
					'name'              => 'productionYear',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'service',
							),
						),
					),
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_612ced9da31382',
					'label'             => 'Model',
					'name'              => 'model',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'service',
							),
						),
					),
					'choices'           => $models,
					'allow_null'        => true,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_3612ce9da31382',
					'label'             => 'Kategorie',
					'name'              => 'services',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'service',
							),
						),
					),
					'choices'           => $services,
					'allow_null'        => true,
					'multiple'          => true,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_60d47ac30f25d',
					'label'             => 'Preferowane modele',
					'name'              => 'preferred_models',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'test-drive',
							),
						),
					),
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60d47a500f25b',
					'label'             => 'Preferowana data',
					'name'              => 'preferred_date',
					'type'              => 'date_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'test-drive',
							),
						),
					),
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'display_format'    => 'Y-m-d',
					'return_format'     => 'Y-m-d',
					'first_day'         => 1,
				),
				array(
					'key'               => 'field_60d47aaa0f25c',
					'label'             => 'Preferowany czas',
					'name'              => 'preferred_time',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_602cec5131383',
								'operator' => '==',
								'value'    => 'test-drive',
							),
						),
					),
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_602ce8d03137f',
					'label'             => 'Zgoda na przetwarzanie danych osobowych',
					'name'              => 'dataProcessingConsent',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_602ce92d31380',
					'label'             => 'Zgoda na kontakt telefoniczny',
					'name'              => 'tradeContactConsent',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_602ce95631381',
					'label'             => 'Zgoda na kontakt mailowy',
					'name'              => 'marketingContactConsent',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '33',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_602ce8bb314de',
					'label'             => 'youLeadData',
					'name'              => 'youLeadData',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'lead',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
