<?php
use Classes\CarDictionary;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\GuzzleException;
$dictionary = new CarDictionary( new GuzzleHttp\Client() );

if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_5c18f89ca825f',
			'title'                 => 'Ustawienia',
			'fields'                => array(
				
				array(
					'key'               => 'field_5c18f8a29941c',
					'label'             => 'Leasing',
					'name'              => 'leasing',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 99,
					'layout'            => 'table',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key' => 'auto_enable',
							'label' => __( 'Włączaj ofertę automatycznie', 'partners-site_v2' ),
							'name' => 'auto_enable',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => [
								'enable' => 'Tak',
								'disable' => 'Nie',
								
							],
							'default_value' => 'disable',
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key'               => 'leasing_description',
							'label' => __( 'Opis dla dealerów', 'partners-site_v2' ),
							'name'              => 'leasing_description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key' => 'exclude_cars',
							'label' => 'Modele wykluczone z oferty',
							'name' => 'exclude_cars',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => $dictionary->getModels(),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'exclude_state',
							'label' => 'Modele wykluczone z oferty',
							'name' => 'exclude_state',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => [
								'nowy' => 'Nowe auta',
								'used' => 'Używane auta',
								'null' => 'Wszystkie auta'
							],
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key'               => 'leasing_pricing',
							'label' => __( 'Wartość pojazdu', 'partners-site_v2' ),
							'name'              => 'leasing_pricing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'netto'  => 'netto',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'leasing_offer',
							'label'             => 'Rodzaj finansowania',
							'name'              => 'leasing_offer',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getLeasingOffer(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_income_leasing',
							'label' => __( 'Domyślna atrakcyjnośc/prowizja', 'partners-site_v2' ),
							'name'              => 'default_income_leasing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'leasing' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_installment_leasing',
							'label' => __( 'Domyślna ilość rat leasingu', 'partners-site_v2' ),
							'name'              => 'default_installment_leasing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'leasing', 'installments' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_fee_leasing',
							'label' => __( 'Domyślna wpłata własna', 'partners-site_v2' ),
							'name'              => 'default_fee_leasing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'leasing', 'entityFee' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'fee_leasing',
							'label' => __( 'Dostępne wpłaty własne', 'partners-site_v2' ),
							'name'              => 'fee_leasing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'leasing', 'entityFee' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 1,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'rates_leasing',
							'label' => __( 'Dostępna ilość rat', 'partners-site_v2' ),
							'name'              => 'rates_leasing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'leasing', 'installments' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 1,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
					),
				),
				array(
					'key'               => 'najem',
					'label'             => 'Najem',
					'name'              => 'najem',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 3,
					'layout'            => 'table',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key' => 'auto_enable',
							'label' => __( 'Włączaj ofertę automatycznie', 'partners-site_v2' ),
							'name' => 'auto_enable',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => [
								'enable' => 'Tak',
								'disable' => 'Nie',
								
							],
							'default_value' => 'disable',
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key'               => 'najem_description',
							'label' => __( 'Opis dla dealerów', 'partners-site_v2' ),
							'name'              => 'najem_description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key' => 'exclude_cars',
							'label' => 'Modele wykluczone z oferty',
							'name' => 'exclude_cars',
							'aria-label' => '',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => $dictionary->getModels(),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'exclude_state',
							'label' => 'Modele wykluczone z oferty',
							'name' => 'exclude_state',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => [
								'nowy' => 'Nowe auta',
								'used' => 'Używane auta',
								'null' => 'Wszystkie auta'
							],
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 1,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key'               => 'najem_pricing',
							'label' => __( 'Wartość pojazdu', 'partners-site_v2' ),
							'name'              => 'najem_pricing',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(								
								'netto'  => 'netto',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'najem_offer',
							'label'             => 'Rodzaj finansowania',
							'name'              => 'najem_offer',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getNajemOffer(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_income_najem',
							'label' => __( 'Domyślna atrakcyjnośc/prowizja', 'partners-site_v2' ),
							'name'              => 'default_income_najem',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'najem' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_installment_najem',
							'label' => __( 'Domyślna ilość rat najmu', 'partners-site_v2' ),
							'name'              => 'default_installment_najem',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'najem', 'installments' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'default_fee_najem',
							'label' => __( 'Domyślna wpłata własna', 'partners-site_v2' ),
							'name'              => 'default_fee_najem',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'najem', 'entityFee' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'fee_najem',
							'label' => __( 'Dostępne wpłaty własne', 'partners-site_v2' ),
							'name'              => 'fee_najem',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'najem', 'entityFee' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 1,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'rates_najem',
							'label' => __( 'Dostępna ilość rat', 'partners-site_v2' ),
							'name'              => 'rates_najem',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => $dictionary->getAttractionSettings( 'najem', 'installments' ),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 1,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'milleage',
							'label' => __( 'Dostępne roczne przebiegi', 'partners-site_v2' ),
							'name'              => 'milleage',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'10' => '10 000',
								'20' => '20 000',
								'30' => '30 000',
								'40' => '40 000',
								'50' => '50 000',
								'60' => '60 000',
								'70' => '70 000',
								'80' => '80 000',
								'90' => '90 000',
								'100' => '100 000',
								'110' => '110 000',
								'120' => '120 000',								
								'130' => '130 000',								
								'140' => '140 000',								
								'150' => '150 000',																
								'160' => '160 000',								
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 1,
							'ui'                => 0,
							'return_format'     => 'key',
							'ajax'              => 0,
							'placeholder'       => '',
						),
					),

				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'options-leasing',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => 1,
			'description'           => '',
		)
	);




}
