<?php

use Classes\CarDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_604a210cc5357',
			'title'                 => 'Wersja wyposażenia',
			'fields'                => array(
				array(
					'key'               => 'field_604a234e3515c',
					'label'             => 'Podstawowe dane',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604b2bef167b7',
					'label'             => 'Nazwa',
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'hide_price',
					'label' => __( 'Wyłącz wyświetlanie ceny', 'partners-site_v2' ),
					'name'              => 'hide_price',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => 'Nie',
						'on' => 'Tak'
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_604a212d35157',
					'label'             => 'Cena',
					'name'              => 'price',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_604a215f35158',
					'label'             => 'Opis',
					'name'              => 'description',
					'type'              => 'textarea',
					'instructions' => __( '(max. 300 znaków)', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => 300,
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_604a238f3515d',
					'label'             => 'Podstawowe dane techniczne',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604a218f35159',
					'label'             => 'Podstawowe dane techniczne',
					'name'              => 'technical-data',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_602b9xb802ced',
							'label'             => 'Rodzaj paliwa',
							'name'              => 'fuel-type',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9bba02ce7',
							'label'             => 'Silnik',
							'name'              => 'engine',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => CarDictionary::getEngines(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_602b1d5802ceb',
							'label'             => 'Moc maksymalna (KM)',
							'name'              => 'max-power-text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_603b9ddd02cee',
							'label'             => 'Czas przyspieszenia (s)',
							'name'              => 'acceleration',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9e2602cef',
							'label' => __( 'Śr. spalanie (litry/100km)', 'partners-site_v2' ),
							'name'              => 'fuel-consumption',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9e9202cf0',
							'label' => __( 'Prędkość maksymalna (km/h)', 'partners-site_v2' ),
							'name'              => 'max-speed',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9ab802cf1',
							'label' => __( 'Pojemność bagażnika (litry)', 'partners-site_v2' ),
							'name'              => 'cargo-capacity',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9ee702cd2',
							'label'             => 'Miejsc',
							'name'              => 'seats',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9efc02cf4',
							'label' => __( 'Wysokość (cm)', 'partners-site_v2' ),
							'name'              => 'height',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9f0d02cf4',
							'label' => __( 'Długość (cm)', 'partners-site_v2' ),
							'name'              => 'length',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9f1d02cf5',
							'label' => __( 'Szerokość z lusterkami (cm)', 'partners-site_v2' ),
							'name'              => 'width',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9f2f02cg6',
							'label' => __( 'Prześwit (cm)', 'partners-site_v2' ),
							'name'              => 'ground-clearance',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_erange',
							'label' => __( 'Zasięg na silniku elektrycznym', 'partners-site_v2' ),
							'name'              => 'erange',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => false,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
					),
				),
				array(
					'key'               => 'field_604a223d3515a',
					'label' => __( 'Link do pełnych danych technicznych', 'partners-site_v2' ),
					'name'              => 'full-technical-data-link',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_604a24042f2c3',
					'label'             => 'Galeria',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604a23263515b',
					'label'             => 'Galeria',
					'name'              => 'gallery',
					'type'              => 'gallery',
					'instructions' => __( '(Zalecana minimalna szerokość: 2877px)', 'partners-site_v2' ),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'insert'            => 'append',
					'library'           => 'all',
					'min'               => '',
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_604b2c5a167b8',
					'label'             => 'Jazda testowa i Konfigurator',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604b2c6c167b9',
					'label'             => 'Jazda testowa i Konfigurator',
					'name'              => 'two-column-content-component',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_604b2cb3167ba',
							'label' => __( 'Tytuł', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' => __( '(max. 40 znaków)', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 40,
						),
						array(
							'key'               => 'field_604b2cbb167bb',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions' => __( '(max. 350 znaków)', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 350,
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_604b2d2c167be',
							'label'             => 'Link do konfiguratora',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_604b2cc4167bc',
							'label' => __( 'Zdjęcie', 'partners-site_v2' ),
							'name'              => 'image',
							'type'              => 'image',
							'instructions' => __( '(Zalecana minimalna szerokość: 2877px)', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'integer',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_version_video',
							'label'             => 'Video Wersji',
							'name'              => 'field_version_video',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,							
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'maximum_selection' => 1,
							'return_format'     => 'url',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => 100,
							'min_height'        => 100,
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_604b2cf6167bd',
							'label'             => 'Video',
							'name'              => 'video',
							'type'              => 'text',
							'instructions'      => 'ID filmu w serwisie youtube.com',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_version_colors',
					'label'             => 'Warianty kolorystyczne',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_version_colors_content',
					'label'             => 'Wiarianty kolorystyczne',
					'name'              => 'field_version_colors_content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key' => 'version_interrior_color_tags',
							'label' => __( 'Wybierz kolor wnętrza', 'partners-site_v2' ),
							'name' => 'version_interrior_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key' => 'version_default_gallery',
							'label' => __( 'Domyślna galeria pojazdu', 'partners-site_v2' ),
							'name' => 'version_default_gallery',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
					array(
					'key'               => 'field_gallery_cards',
					'label'             => 'Karty',
					'name'              => 'cards',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_gallery_cards_inside',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key' => 'version_color_tags',
							'label' => 'Wybierz kolor',
							'name' => 'version_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key'               => 'gallery_type',
							'label'             => 'Rodzaj galleri',
							'name'              => 'gallery_type',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'choices'           => [
								'auto' => 'auto',
								'inside' => 'wnętrze'
							],
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'version_gallery',
							'label' => __( 'Zdjęcia wersji kolorystycznej', 'partners-site_v2' ),
							'name'              => 'version_gallery',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => 100,
							'min_height'        => 100,
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
		),
	),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'child',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}
