<?php
if ( function_exists( 'acf_add_local_field_group' ) ) {

	acf_add_local_field_group(
		array(
			'key'                   => 'group_604a1c922f8ed',
			'title'                 => __('Models', 'partners-site_v2'),
			'fields'                => array(
				array(
					'key'               => 'field_604a1c9f94d09',
					'label'             => __('Type', 'partners-site_v2'),
					'name'              => 'type',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'suv'           => __('SUV', 'partners-site_v2'),
						'crossover'         => __('Crossover', 'partners-site_v2'),
						'sedan'         => __('Sedan', 'partners-site_v2'),
						
						'kombi'         => __( 'Station wagon', 'partners-site_v2' ),
						'cross-country' => __('Cross Country', 'partners-site_v2'),
						
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_604a20569d149',
					'label'             => __('Model Name', 'partners-site_v2'),
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'testDrive',
					'label'             => __('Should the car be available for a "test drive"?', 'partners-site_v2'),
					'name'              => 'testDrive',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				), 
				array(
					'key'               => 'short_name_list',
					'label' => __('Model Short Name in the Car List', 'partners-site_v2'),
					'name'              => 'short_name_list',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_604a20569d140',
					'label' => __('Model Short Name', 'partners-site_v2'),
					'name'              => 'short-name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_604a20939d141',
					'label' => __('Thumbnail Image in the Menu', 'partners-site_v2'),
					'name'              => 'thumbnail',
					'type'              => 'image',
					'instructions' => __('(Recommended minimum width: 420px)', 'partners-site_v2'),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'menu_price',
					'label' => __('Vehicle price on the thumbnail in the models tab', 'partners-site_v2'),
					'name'              => 'menu_price',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '25',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_version_colors',
					'label'             => __('Color variants', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_version_colors_content',
					'label'             => __('Color variants', 'partners-site_v2'),
					'name'              => 'field_version_colors_content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key' => 'version_interrior_color_tags',
							'label' => __('Select interior color', 'partners-site_v2'),
							'name' => 'version_interrior_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key' => 'version_default_gallery',
							'label' => __('Default vehicle gallery', 'partners-site_v2'),
							'name' => 'version_default_gallery',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 1,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
					array(
					'key'               => 'field_gallery_cards',
					'label'             => __('Tabs', 'partners-site_v2'),
					'name'              => 'cards',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_gallery_cards_inside',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key' => 'version_color_tags',
							'label' => __('Select color', 'partners-site_v2'),
							'name' => 'version_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key'               => 'gallery_type',
							'label'             => __('Gallery type', 'partners-site_v2'),
							'name'              => 'gallery_type',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'choices'           => [
								'auto' => __( 'Gallery_Car', 'partners-site_v2' ),
								'inside' => __( 'Gallery_interior', 'partners-site_v2' )
							],
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'version_gallery',
							'label' => __('Photos of the color variant', 'partners-site_v2'),
							'name'              => 'version_gallery',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => 100,
							'min_height'        => 100,
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
		),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
					array(
						'param'    => 'page_type',
						'operator' => '!=',
						'value'    => 'child',
					),
				),
			),
			'hide_on_screen'        => array(
				0 => 'the_content',
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'active'                => true,
			'description'           => '',
		)
	);

}
