<?php

use Classes\CarDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_604a210cc5357',
			'title'                 => __( 'Equipment Version', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_604a234e3515c',
					'label'             => __('Basic data', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604b2bef167b7',
					'label'             => __('Name', 'partners-site_v2'),
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'hide_price',
					'label' => __('Hide price', 'partners-site_v2'),
					'name'              => 'hide_price',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'off'  => __( 'No', 'partners-site_v2' ),
						'on' => __( 'Yes', 'partners-site_v2' )
					),
					'default_value'     => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_604a212d35157',
					'label'             => __('Price', 'partners-site_v2'),
					'name'              => 'price',
					'type'              => 'number',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'min'               => '',
					'max'               => '',
					'step'              => '',
				),
				array(
					'key'               => 'field_604a215f35158',
					'label'             => __( 'Description', 'partners-site_v2' ),
					'name'              => 'description',
					'type'              => 'textarea',
					'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 300),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => 300,
					'rows'              => '',
					'new_lines'         => '',
				),
				array(
					'key'               => 'field_604a238f3515d',
					'label'             => __('Basic Technical Specifications', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604a218f35159',
					'label'             => __('Basic Technical Specifications', 'partners-site_v2'),
					'name'              => 'technical-data',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_602b9xb802ced',
							'label'             => __('Fuel Type', 'partners-site_v2'),
							'name'              => 'fuel-type',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9bba02ce7',
							'label'             => __('Engine', 'partners-site_v2'),
							'name'              => 'engine',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => CarDictionary::getEngines(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_602b1d5802ceb',
							'label'             => __('Maximum Power (HP)', 'partners-site_v2'),
							'name'              => 'max-power-text',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_603b9ddd02cee',
							'label'             => __('Acceleration time (s)', 'partners-site_v2'),
							'name'              => 'acceleration',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9e2602cef',
							'label' => __('Average fuel consumption (liters/100 km)', 'partners-site_v2'),
							'name'              => 'fuel-consumption',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9e9202cf0',
							'label' => __( 'Maximum speed (km/h)', 'partners-site_v2' ),
							'name'              => 'max-speed',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9ab802cf1',
							'label' => __( 'Trunk capacity (liters)', 'partners-site_v2' ),
							'name'              => 'cargo-capacity',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9ee702cd2',
							'label'             => __( 'Seats', 'partners-site_v2' ),
							'name'              => 'seats',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9efc02cf4',
							'label' => __( 'Height (cm)', 'partners-site_v2' ),
							'name'              => 'height',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9f0d02cf4',
							'label' => __( 'Length (cm)', 'partners-site_v2' ),
							'name'              => 'length',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_602b9f1d02cf5',
							'label' => __( 'Width with mirrors (cm)', 'partners-site_v2' ),
							'name'              => 'width',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_602b9f2f02cg6',
							'label' => __( 'Ground clearance (cm)', 'partners-site_v2' ),
							'name'              => 'ground-clearance',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
						array(
							'key'               => 'field_erange',
							'label' => __('Electric range', 'partners-site_v2'),
							'name'              => 'erange',
							'type'              => 'number',
							'instructions'      => '',
							'required'          => false,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'min'               => '',
							'max'               => '',
							'step'              => '',
						),
					),
				),
				array(
					'key'               => 'field_604a223d3515a',
					'label' => __('Link to full technical specifications', 'partners-site_v2'),
					'name'              => 'full-technical-data-link',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_604a24042f2c3',
					'label'             => __( 'Gallery', 'partners-site_v2' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604a23263515b',
					'label'             => __( 'Gallery', 'partners-site_v2' ),
					'name'              => 'gallery',
					'type'              => 'gallery',
					'instructions' => __('(Recommended minimum width: 2877px)', 'partners-site_v2'),
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'insert'            => 'append',
					'library'           => 'all',
					'min'               => '',
					'max'               => '',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_604b2c5a167b8',
					'label'             => __('Test Drive and Configurator', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_604b2c6c167b9',
					'label'             => __('Test Drive and Configurator', 'partners-site_v2'),
					'name'              => 'two-column-content-component',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_604b2cb3167ba',
							'label' => __( 'Title', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 40),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 40,
						),
						array(
							'key'               => 'field_604b2cbb167bb',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 350),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 350,
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_604b2d2c167be',
							'label'             => __('Link to configurator', 'partners-site_v2'),
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_604b2cc4167bc',
							'label' => __( 'Photo', 'partners-site_v2' ),
							'name'              => 'image',
							'type'              => 'image',
							'instructions' => __('(Recommended minimum width: 2877px)', 'partners-site_v2'),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'integer',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_version_video',
							'label'             => __('Video of the version', 'partners-site_v2'),
							'name'              => 'field_version_video',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,							
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'maximum_selection' => 1,
							'return_format'     => 'url',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => 100,
							'min_height'        => 100,
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'field_604b2cf6167bd',
							'label'             => __('Video', 'partners-site_v2'),
							'name'              => 'video',
							'type'              => 'text',
							'instructions'      => __( 'Video ID on youtube.com', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_version_colors',
					'label'             => __('Color variants', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_version_colors_content',
					'label'             => __('Color variants', 'partners-site_v2'),
					'name'              => 'field_version_colors_content',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key' => 'version_interrior_color_tags',
							'label' => __('Select interior color', 'partners-site_v2'),
							'name' => 'version_interrior_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key' => 'version_default_gallery',
							'label' => __('Default vehicle gallery', 'partners-site_v2'),
							'name' => 'version_default_gallery',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
					array(
					'key'               => 'field_gallery_cards',
					'label'             => __('Tabs', 'partners-site_v2'),
					'name'              => 'cards',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_gallery_cards_inside',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key' => 'version_color_tags',
							'label' => __('Select color', 'partners-site_v2'),
							'name' => 'version_color_tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'model_category_colors',
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => false,
							'bidirectional_target' => array(),
						),
						array(
							'key'               => 'gallery_type',
							'label'             => __('Gallery type', 'partners-site_v2'),
							'name'              => 'gallery_type',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'choices'           => [
								'auto' => __( 'Gallery_Car', 'partners-site_v2' ),
								'inside' => __( 'Gallery_interior', 'partners-site_v2' )
							],
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'version_gallery',
							'label' => __('Photos of the color variant', 'partners-site_v2'),
							'name'              => 'version_gallery',
							'type'              => 'gallery',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'url',
							'preview_size'      => 'thumbnail',
							'library'           => 'all',
							'min_width'         => 100,
							'min_height'        => 100,
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
		),
	),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'model',
					),
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'child',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}
