<?php

// use Classes\IconsDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_603cfb36c8877',
			'title'                 => __('OfferBoxes', 'partners-site_v2'),
			'fields'                => array(
				array(
					'key'               => 'field_605ce9505becc',
					'label'             => __('Layout', 'partners-site_v2'),
					'name'              => 'layout',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'three-in-row' => __( 'Three in row', 'partners-site_v2' ),
						'two-in-row'   => __( 'Two in row', 'partners-site_v2' ),
					),
					'default_value'     => 'three-in-row',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'pull_up',
					'label' => __('Tiles overlapping the banner?', 'partners-site_v2'),
					'name'              => 'pull_up',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'choices'           => array(
						'tak' => __( 'yes', 'partners-site_v2' ),

					),
					'allow_null'        => true,
					'multiple'          => false,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'iconView',
					'label'             => __('Visible icons and text aligned to the left', 'partners-site_v2'),
					'name'              => 'iconview',
					'type'              => 'checkbox', 
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'choices'           => array(
						'tak' => __( 'yes', 'partners-site_v2' ), 

					),
					'allow_null'        => true,
					'multiple'          => false,
					'wrapper'           => array(
						'width' => '50',
						'class' => '',
						'id'    => '',
					),
					'default_value' => array( 'tak' ),
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_603cfb40f335c',
					'label'             => __('Elements', 'partners-site_v2'),
					'name'              => 'items',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => '',
					'sub_fields'        => array(
						array(
							'key'               => 'field_605f69b30f61f',
							'label'             => __('Icon', 'partners-site_v2'),
							'name'              => 'icon',
							'type'              => 'icon_select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => [], //IconsDictionary::getIcons(),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'return_format'     => 'value',
							'ui'                => 1,
							'ajax'              => 0,
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_603cfb61f335e',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '40',
						),
						array(
							'key'               => 'field_603cfb6af335f',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '400',
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_603cfb72f33601',
							'label'             => __( 'Link', 'partners-site_v2' ),
							'name'              => 'link',
							'type'              => 'custom_link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'text_choices'      => array( 'Czytaj dalej', 'Więcej' ),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/offer-boxes',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
