<?php

use Classes\IconsDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6062210c411fe',
			'title'                 => __( 'Service', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_606222183bd26',
					'label'             => __('Slider', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_606222213bd27',
					'label'             => __('Slider', 'partners-site_v2'),
					'name'              => 'service-slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606222353bd28',
							'label' => __('Campaigns displayed on the slider', 'partners-site_v2'), 
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => __('Add campaign', 'partners-site_v2'),
							'sub_fields'        => array(
								array(
									'key'               => 'field_606222543bd29',
									'label'             => __('Campaign type', 'partners-site_v2'),
									'name'              => 'type',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'local'  => __( 'Local campaign', 'partners-site_v2' ),
										'global' => __( 'Global campaign', 'partners-site_v2' ),
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_606222863bd2a',
									'label'             => __( 'Campaign', 'partners-site_v2' ),
									'name'              => 'local-campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_606222543bd29',
												'operator' => '==',
												'value'    => 'local',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key'               => 'field_606222ac3bd2b',
									'label'             => __( 'Campaign', 'partners-site_v2' ),
									'name'              => 'global-campaign',
									'type'              => 'network_post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_606222543bd29',
												'operator' => '==',
												'value'    => 'global',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606222213bd273',
					'label'             => __('Slider', 'partners-site_v2'),
					'name'              => 'global-service-slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606222213bd274',
							'label' => __( 'Campaigns displayed in the slider', 'partners-site_v2' ),
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => __('Add campaign', 'partners-site_v2'),
							'sub_fields'        => array(
								array(
									'key'               => 'field_606222213bd275',
									'label'             => __( 'Campaign', 'partners-site_v2' ),
									'name'              => 'campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_6062230f573c0',
					'label'             => __('List of benefits', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'main-site-only'    => true,
				),
				array(
					'key'               => 'field_60622319573c1',
					'label'             => __('List of benefits', 'partners-site_v2'),
					'name'              => 'advantages-list',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062232c573c2',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 75),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 75,
						),
						array(
							'key'               => 'field_6062234f573c3',
							'label'             => __( 'Description', 'partners-site_v2' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 160),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 160,
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_6062232c573c3',
							'label' => __('Text for the button to expand lists on mobile devices', 'partners-site_v2'),
							'name'              => 'more-text',
							'type'              => 'text',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 75),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 75,
						),
						array(
							'key'               => 'field_60622380573c4',
							'label'             => __('Items in the left column', 'partners-site_v2'),
							'name'              => 'list1',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622389573c5',
									'label'             => __('Text', 'partners-site_v2'),
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 160),
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => 160,
									'rows'              => 4,
									'new_lines'         => '',
								),
							),
						),
						array(
							'key'               => 'field_60622380ad3c4',
							'label'             => __('Items in the right column', 'partners-site_v2'),
							'name'              => 'list2',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622389573c5',
									'label'             => __('Text', 'partners-site_v2'),
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 160),
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => 160,
									'rows'              => 4,
									'new_lines'         => '',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606223ac573c6',
					'label'             => __( 'Form', 'partners-site_v2' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'main-site-only'    => true,
				),
				array(
					'key'               => 'field_606223e8573c7',
					'label'             => __( 'Form', 'partners-site_v2' ),
					'name'              => 'form',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606223fe573c8',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions' => __( 'By default, the header text is gray. <br>To make a phrase black, please place it between &lt;strong&gt;&lt;/strong&gt;,<br>e.g., &lt;strong&gt;TEXT&lt;/strong&gt;. <br>To add a line break, please add &lt;br&gt;, e.g., TEXT &lt;br&gt;TEXT', 'partners-site_v2' ),
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6062242c573c9',
							'label'             => __('Models to choose from', 'partners-site_v2'),
							'name'              => 'models',
							'type'              => 'repeater',
							'instructions' => __('All Volvo models available to select when filling out the form', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622460573ca',
									'label'             => __('Name', 'partners-site_v2'),
									'name'              => 'name',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_606224c3573cb',
							'label' => __('Services', 'partners-site_v2'),
							'name'              => 'services',
							'type'              => 'repeater',
							'instructions' => __('All services available to select when filling out the form', 'partners-site_v2'),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_606224de573cc',
									'label'             => __('Icon', 'partners-site_v2'),
									'name'              => 'icon',
									'type'              => 'icon_select',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => IconsDictionary::getIcons(),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'value',
									'ui'                => 1,
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_606224f2573cd',
									'label'             => __('Name', 'partners-site_v2'),
									'name'              => 'name',
									'type'              => 'text',
									'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 75),
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 75,
								),
								array(
									'key'               => 'field_60622500573ce',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'visual',
									'toolbar'           => 'blog',
									'media_upload'      => 1,
									'delay'             => 0,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606225ef573cf',
					'label' => __('Service options', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60622604573d0',
					'label' => __('Service options', 'partners-site_v2'),
					'name'              => 'services-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062261c573d1',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'main-site-only'    => true,
						),
						array(
							'key'               => 'field_6062262b573d2',
							'label' => __('Services', 'partners-site_v2'),
							'name'              => 'services',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'row',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6062264a573d3',
									'label' => __( 'Title', 'partners-site_v2' ),
									'name'              => 'heading',
									'type'              => 'text',
									'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 75),
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 75,
								),
								array(
									'key'               => 'field_60622659573d4',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'description',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'visual',
									'toolbar'           => 'blog',
									'media_upload'      => 1,
									'delay'             => 0,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_60622673573d5',
					'label'             => __('Service contact', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60622681573d6',
					'label'             => __('Service contact', 'partners-site_v2'),
					'name'              => 'contact-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062268d573d7',
							'label' => __( 'Header', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'main-site-only'    => true,
						),
						array(
							'key'               => 'field_606226d4573d8',
							'label'             => __('Contact persons', 'partners-site_v2'),
							'name'              => 'employees',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'child-site-only'   => true,
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622708573d9',
									'label'             => __('Specializations', 'partners-site_v2'),
									'name'              => 'specializations',
									'type'              => 'repeater',
									'instructions'      => __( '(up to 3 specializations)', 'partners-site_v2' ),
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 3,
									'layout'            => 'table',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6062273e573da',
											'label'        => __('Specialization name', 'partners-site_v2'),
											'name'         => 'name',
											'type'         => 'text',
											'instructions' => sprintf(__( '(max. %s chars_)', 'partners-site_v2' ), 22),
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => 22,
										),
									),
								),
								array(
									'key'               => 'field_60622763573db',
									'label'             => __( 'Employee', 'partners-site_v2' ),
									'name'              => 'employee',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'employee',
									),
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'vinomat_boxes',
					'label'             => __('Offer boxes', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'vinomat_boxes_section',
					'label'             => __('Service contact', 'partners-site_v2'),
					'name'              => 'vinomat-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'vinomat_news_dealer',
							'label'             => __('Vinomat information box', 'partners-site_v2'),
							'name'              => 'vinomat_news',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'vinomat_news_title',
									'label' => __( 'Title', 'partners-site_v2' ),
									'name'              => 'vinomat_news_title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'vinomat_news_desc',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'vinomat_news_desc',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'vinomat_news_image',
									'label' => __( 'Photo', 'partners-site_v2' ),
									'name'              => 'vinomat_news_image',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'integer',
									'preview_size'      => 'small',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'vinomat_box_link',
									'label'             => __('Link to campaign', 'partners-site_v2'),
									'name'              => 'slides',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 1,
									'layout'            => 'row',
									'button_label'      => __('Add campaign', 'partners-site_v2'),
									'sub_fields'        => array(
										array(
											'key'          => 'vinomat_box_link_type',
											'label'        => __('Campaign type', 'partners-site_v2'),
											'name'         => 'type',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'local'  => __( 'Local campaign', 'partners-site_v2' ),
												'global' => __( 'Global campaign', 'partners-site_v2' ),
											),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'vinomat_box_link_type_1',
											'label'        => __( 'Campaign', 'partners-site_v2' ),
											'name'         => 'local-campaign',
											'type'         => 'post_object',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'vinomat_box_link_type',
														'operator' => '==',
														'value'    => 'local',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => 'campaign',
											),
											'taxonomy'     => '',
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'id',
											'ui'           => 1,
										),
										array(
											'key'          => 'vinomat_box_link_type_2',
											'label'        => __( 'Campaign', 'partners-site_v2' ),
											'name'         => 'global-campaign',
											'type'         => 'network_post_object',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'vinomat_box_link_type',
														'operator' => '==',
														'value'    => 'global',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => 'campaign',
											),
											'taxonomy'     => '',
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'id',
											'ui'           => 1,
										),
									),
								),
							),
						),
					),
				),
				array(
					'key' => 'service_additional',
					'label' => __('Additional settings', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'service_additional_section',
					'label' => __('Code for thank-you page', 'partners-site_v2'),
					'name' => 'service-section',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_thankyou_code',
							'label' => __( 'Additional code for the thank-you page', 'partners-site_v2' ),
							'name' => 'field_thankyou_code',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'options-service',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'autoload' => true,
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
