<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_60212d5a0c0cd',
			'title'                 => __('Preview Component', 'partners-site_v2'),
			'fields'                => array(
				array(
					'key'               => 'field_6021460e4e06c',
					'label' => __( 'Photo', 'partners-site_v2' ),
					'name'              => 'img',
					'type'              => 'image',
					'instructions' => __('Please verify that the content height does not exceed the image height<br>(minimum image width: 944px, recommended width: 2832px)', 'partners-site_v2'),
					'required'          => 0,
					'conditional_logic' => 0, 
					'wrapper'           => array( 
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium', 
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_602146c1443c4',
					'label'             => __('Image position', 'partners-site_v2'),
					'name'              => 'image-position',
					'type'              => 'radio',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'left'  => __( 'Left', 'partners-site_v2' ),
						'right' => __( 'Right', 'partners-site_v2' ),
					),
					'allow_null'        => 0,
					'other_choice'      => 0,
					'default_value'     => 'left',
					'layout'            => 'horizontal',
					'return_format'     => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key'               => 'headingTag', 
					'label'             => __('Header type', 'partners-site_v2'),
					'name'              => 'heading_tag',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices' => array(
						'h1' => 'H1',
						'h2' => 'H2',
						'h3' => 'H3',
						'h4' => 'H4',
						'h5' => 'H5',
						'h6' => 'H6',
					),
					'default_value' => 'h2',
					'allow_null'    => 0,
					'multiple'      => 0,
					'ui'            => 0, 
					'return_format' => 'value',
				),
				
				array(
					'key'               => 'field_602146ff443c5',
					'label' => __( 'Header', 'partners-site_v2' ),
					'name'              => 'heading',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_60214709443c6',
					'label' => __( 'Content', 'partners-site_v2' ),
					'name'              => 'content',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'layout_60214709443c9'  => array(
							'key'        => 'layout_60214709443c9',
							'name'       => 'description',
							'label'      => __( 'Description', 'partners-site_v2' ),
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_60214709445437',
									'label'             => __( 'Description', 'partners-site_v2' ),
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => '',
									'new_lines'         => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_60214709443c10' => array(
							'key'        => 'layout_60214709443c10',
							'name'       => 'contact-info',
							'label'      => __( 'Contact person', 'partners-site_v2' ),
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_60214709443426',
									'label'             => __( 'Contact person', 'partners-site_v2' ),
									'name'              => 'contact-info',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'employee',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_60214709443c11' => array(
							'key'        => 'layout_60214709443c11',
							'name'       => 'list',
							'label'      => __('List of benefits', 'partners-site_v2'),
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_60214709443654',
									'label'             => __('List of benefits', 'partners-site_v2'),
									'name'              => 'list',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 0,
									'layout'            => 'table',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_60214709443654a',
											'label'        => __('Text', 'partners-site_v2'),
											'name'         => 'text',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_60214709443c12' => array(
							'key'        => 'layout_60214709443c12',
							'name'       => 'link',
							'label'      => __( 'Button', 'partners-site_v2' ),
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_6021470944995',
									'label'             => __( 'Button action', 'partners-site_v2' ),
									'name'              => 'buttonAction',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'link' => __( 'Link', 'partners-site_v2' ),
										'form' => __( 'Form', 'partners-site_v2' ),
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_6021470944996',
									'label'             => __( 'Button Text', 'partners-site_v2' ),
									'name'              => 'buttonText',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_6021470944995',
												'operator' => '==',
												'value'    => 'form',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_6021470944994',
									'label'             => __( 'Link', 'partners-site_v2' ),
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_6021470944995',
												'operator' => '==',
												'value'    => 'link',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_60214709443c13' => array(
							'key'        => 'layout_60214709443c13',
							'name'       => 'table',
							'label'      => __( 'Table', 'partners-site_v2' ),
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_602147094449e',
									'label'             => __( 'Table', 'partners-site_v2' ),
									'name'              => 'table',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 0,
									'layout'            => 'table',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_602147094449ea',
											'label'        => __('Label', 'partners-site_v2'),
											'name'         => 'label',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '50',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_602147094449eb',
											'label' => __('Value', 'partners-site_v2'),
											'name'         => 'value',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '50',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
									),
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => __( 'Add Content', 'partners-site_v2' ),
					'min'               => '',
					'max'               => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/preview-component',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
