<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6051cd52bb16f',
			'title'                 => __( 'Showroom', 'partners-site_v2' ),
			'fields'                => array(
				array(
					'key'               => 'field_6051cfffc4f4e',
					'label'             => __( 'Basic Information', 'partners-site_v2' ),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051cd9117f12',
					'label'             => __('Showroom ID', 'partners-site_v2'),
					'name'              => 'showroomId',
					'type'              => 'text',
					'instructions' => __('Full dealership showroom ID, e.g., <strong>PL100#1</strong>', 'partners-site_v2'),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'admin-only'        => true,
				),
				array(
					'key'               => 'field_60b4d37267g4d',
					'label'             => __('Has a showroom', 'partners-site_v2'),
					'name'              => 'has-showroom',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => true,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60b4d37267f4d',
					'label'             => __('Has a service center', 'partners-site_v2'),
					'name'              => 'has-service',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60b4d37267f4f',
					'label' => __('Has a Customer Service Office', 'partners-site_v2'),
					'name'              => 'has-customer-service-office',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_6051cd8117f12',
					'label'             => __('Showroom name', 'partners-site_v2'),
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'required-multi-showroom-and-service-only' => true,
				),
				array(
					'key'               => 'field_6051cd8c17f13',
					'label'             => __( 'Address', 'partners-site_v2' ),
					'name'              => 'address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051cda717f14',
							'label'             => __('Street', 'partners-site_v2'),
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6051cdb317f15',
							'label'             => __('Zip code', 'partners-site_v2'),
							'name'              => 'zip-code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'xx-xxx',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 6,
						),
						array(
							'key'               => 'field_6051ce5217f16',
							'label'             => __( 'City', 'partners-site_v2' ),
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6051ce6317f17',
							'label'             => __( 'Phone Number', 'partners-site_v2' ),
							'name'              => 'phone',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051cf3117f20',
					'label'             => __('Location on map', 'partners-site_v2'),
					'name'              => 'map-position',
					'type'              => 'google_map',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'center_lat'        => '51.9194',
					'center_lng'        => '19.1451',
					'zoom'              => '6',
					'height'            => '',
				),
				array(
					'key'               => 'field_6051cd8117f22',
					'label' => __('Showroom city', 'partners-site_v2'),
					'name'              => 'showroom-location',
					'type'              => 'text',
					'instructions' => __('Showroom city to be used on the website odreki.poznajvolvo.pl', 'partners-site_v2'),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'admin-only'        => true,
				),
				array(
					'key'               => 'field_6051d00bc4f4f',
					'label'             => __('Showroom hours', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267g4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051ce7917f18',
					'label'             => __('Showroom hours', 'partners-site_v2'),
					'name'              => 'showroom-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267g4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051ce9c17f19',
							'label' => __('Monday-Friday', 'partners-site_v2'),
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa1a6ee2b',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa2f6ee2c',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa426ee2d',
							'label'             => __('Saturday', 'partners-site_v2'),
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa426ee2e',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa426ee2f',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051cee517f1b',
							'label'             => __('Additional information', 'partners-site_v2'),
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 100),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051d018c4f50',
					'label'             => __('Service center opening hours', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051fa4c6ee30',
					'label'             => __('Service center opening hours', 'partners-site_v2'),
					'name'              => 'service-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051fa4c6ee31',
							'label' => __('Monday-Friday', 'partners-site_v2'),
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa4c6ee32',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa4c6ee33',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa4c6ee34',
							'label'             => __('Saturday', 'partners-site_v2'),
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa4c6ee35',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa4c6ee36',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa4c6ee37',
							'label'             => __('Additional information', 'partners-site_v2'),
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 100),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051d018c4f51',
					'label' => __('Customer Service Office opening hours', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4f',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051d018c4f52',
					'label' => __('Customer Service Office opening hours', 'partners-site_v2'),
					'name'              => 'customer-service-office-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4f',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051d018c4f53',
							'label' => __('Monday-Friday', 'partners-site_v2'),
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051d018c4f54',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051d018c4f55',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051d018c4f56',
							'label'             => __('Saturday', 'partners-site_v2'),
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051d018c4f57',
									'label'             => __('From', 'partners-site_v2'),
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051d018c4f58',
									'label'             => __('To', 'partners-site_v2'),
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051d018c4f59',
							'label'             => __('Additional information', 'partners-site_v2'),
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions' 		=> sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 100),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_showroom_departments_hours_tab',
					'label'             => __('Department opening hours', 'partners-site_v2'),
					'name'              => '',
					'type'              => 'tab',
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key' => 'field_departments_hours',
					'label' => __('Department hours', 'partners-site_v2'),
					'name' => 'departments_hours',
					'type' => 'group',
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_department_0_title',
							'label' => __('Business Development Center', 'partners-site_v2'),
							'name' => 'department_0_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_0_name',
							'label' => __('Business Development Center', 'partners-site_v2'),
							'name' => 'department_0_name',
							'type' => 'text',
							'default_value' => 'business_development_center',
							 
						),
						array(
							'key' => 'field_department_hours_business_development_center',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_business_development_center',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_business_development_center',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_business_development_center',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_business_development_center',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_business_development_center',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_business_development_center',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_business_development_center',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_1_title',
							'label' => __('Assistance', 'partners-site_v2'),
							'name' => 'department_1_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_1_name',
							'label' => __('Assistance', 'partners-site_v2'),
							'name' => 'department_1_name',
							'type' => 'text',
							'default_value' => 'assistance', 
						),
						
						array(
							'key' => 'field_department_hours_assistance',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_assistance',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_assistance',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_assistance',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_assistance',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_assistance',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_assistance',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_assistance',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_2_title',
							'label' => __('Auto Insurance', 'partners-site_v2'),
							'name' => 'department_2_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_2_name',
							'label' => __('Auto Insurance', 'partners-site_v2'),
							'name' => 'department_2_name',
							'type' => 'text',
							'default_value' => 'ubezpieczenia_komunikacyjne', 
						),
						array(
							'key' => 'field_department_hours_ubezpieczenia_komunikacyjne',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_ubezpieczenia_komunikacyjne',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_ubezpieczenia_komunikacyjne',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_ubezpieczenia_komunikacyjne',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_ubezpieczenia_komunikacyjne',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_ubezpieczenia_komunikacyjne',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_ubezpieczenia_komunikacyjne',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_ubezpieczenia_komunikacyjne',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_3_title',
							'label' => __('New cars', 'partners-site_v2'),
							'name' => 'department_3_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_3_name',
							'label' => __('New cars', 'partners-site_v2'),
							'name' => 'department_3_name',
							'type' => 'text',
							'default_value' => 'samochody_nowe', 
						),
						array(
							'key' => 'field_department_hours_samochody_nowe',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_samochody_nowe',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_samochody_nowe',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_samochody_nowe',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_samochody_nowe',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_samochody_nowe',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_samochody_nowe',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_samochody_nowe',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_4_title',
							'label' => __('Wadowscy Auto Detailing', 'partners-site_v2'),
							'name' => 'department_4_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_4_name',
							'label' => __('Wadowscy Auto Detailing', 'partners-site_v2'),
							'name' => 'department_4_name',
							'type' => 'text',
							'default_value' => 'wadowscy_auto_detailing', 
						),
						array(
							'key' => 'field_department_hours_wadowscy_auto_detailing',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_wadowscy_auto_detailing',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_wadowscy_auto_detailing',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_wadowscy_auto_detailing',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_wadowscy_auto_detailing',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_wadowscy_auto_detailing',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_wadowscy_auto_detailing',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_wadowscy_auto_detailing',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_5_title',
							'label' => __( 'Service', 'partners-site_v2' ),
							'name' => 'department_5_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_5_name',
							'label' => __( 'Service', 'partners-site_v2' ),
							'name' => 'department_5_name',
							'type' => 'text',
							'default_value' => 'serwis', 
						),
						array(
							'key' => 'field_department_hours_serwis',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_serwis',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_serwis',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_serwis',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_serwis',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_serwis',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_serwis',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_serwis',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_6_title',
							'label' => __('Parts and Accessories', 'partners-site_v2'),
							'name' => 'department_6_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_6_name',
							'label' => __('Parts and Accessories', 'partners-site_v2'),
							'name' => 'department_6_name',
							'type' => 'text',
							'default_value' => 'czesci_i_akcesoria', 
						),
						array(
							'key' => 'field_department_hours_czesci_i_akcesoria',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_czesci_i_akcesoria',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_czesci_i_akcesoria',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_czesci_i_akcesoria',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_czesci_i_akcesoria',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_czesci_i_akcesoria',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_czesci_i_akcesoria',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_czesci_i_akcesoria',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_7_title',
							'label' => __('Online Sales of Parts and Accessories', 'partners-site_v2'),
							'name' => 'department_7_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_7_name',
							'label' => __('Online Sales of Parts and Accessories', 'partners-site_v2'),
							'name' => 'department_7_name',
							'type' => 'text',
							'default_value' => 'sprzedaz_internetowa_czesci_i_akcesoriow', 
						),
						array(
							'key' => 'field_department_hours_sprzedaz_internetowa_czesci_i_akcesoriow',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_sprzedaz_internetowa_czesci_i_akcesoriow',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_sprzedaz_internetowa_czesci_i_akcesoriow',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_sprzedaz_internetowa_czesci_i_akcesoriow',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_sprzedaz_internetowa_czesci_i_akcesoriow',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_sprzedaz_internetowa_czesci_i_akcesoriow',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_sprzedaz_internetowa_czesci_i_akcesoriow',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_sprzedaz_internetowa_czesci_i_akcesoriow',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_8_title',
							'label' => __('Fleet Sales', 'partners-site_v2'),
							'name' => 'department_8_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_8_name',
							'label' => __('Fleet Sales', 'partners-site_v2'),
							'name' => 'department_8_name',
							'type' => 'text',
							'default_value' => 'sprzedaz_flotowa', 
						),
						array(
							'key' => 'field_department_hours_sprzedaz_flotowa',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_sprzedaz_flotowa',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_sprzedaz_flotowa',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_sprzedaz_flotowa',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_sprzedaz_flotowa',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_sprzedaz_flotowa',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_sprzedaz_flotowa',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_sprzedaz_flotowa',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_9_title',
							'label' => __('Volvo Service Club', 'partners-site_v2'),
							'name' => 'department_9_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_9_name',
							'label' => __('Volvo Service Club', 'partners-site_v2'),
							'name' => 'department_9_name',
							'type' => 'text',
							'default_value' => 'volvo_service_club', 
						),
						array(
							'key' => 'field_department_hours_volvo_service_club',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_volvo_service_club',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_volvo_service_club',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_volvo_service_club',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_volvo_service_club',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_volvo_service_club',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_volvo_service_club',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_volvo_service_club',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_10_title',
							'label' => __('Bodywork and Paint Service', 'partners-site_v2'),
							'name' => 'department_10_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_10_name',
							'label' => __('Bodywork and Paint Service', 'partners-site_v2'),
							'name' => 'department_10_name',
							'type' => 'text',
							'default_value' => 'serwis_blacharsko_lakierniczy', 
						),
						array(
							'key' => 'field_department_hours_serwis_blacharsko_lakierniczy',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_serwis_blacharsko_lakierniczy',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_serwis_blacharsko_lakierniczy',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_serwis_blacharsko_lakierniczy',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_serwis_blacharsko_lakierniczy',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_serwis_blacharsko_lakierniczy',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_serwis_blacharsko_lakierniczy',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_serwis_blacharsko_lakierniczy',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_11_title',
							'label' => __('Used cars', 'partners-site_v2'),
							'name' => 'department_11_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_11_name',
							'label' => __('Used cars', 'partners-site_v2'),
							'name' => 'department_11_name',
							'type' => 'text',
							'default_value' => 'samochody_uzywane', 
						),
						array(
							'key' => 'field_department_hours_samochody_uzywane',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_samochody_uzywane',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_samochody_uzywane',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_samochody_uzywane',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_samochody_uzywane',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_samochody_uzywane',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_samochody_uzywane',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_samochody_uzywane',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_12_title',
							'label' => __('Financing and Insurance', 'partners-site_v2'),
							'name' => 'department_12_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_12_name',
							'label' => __('Financing and Insurance', 'partners-site_v2'),
							'name' => 'department_12_name',
							'type' => 'text',
							'default_value' => 'finansowanie_i_ubezpieczenia', 
						),
						array(
							'key' => 'field_department_hours_finansowanie_i_ubezpieczenia',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_finansowanie_i_ubezpieczenia',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_finansowanie_i_ubezpieczenia',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_finansowanie_i_ubezpieczenia',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_finansowanie_i_ubezpieczenia',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_finansowanie_i_ubezpieczenia',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_finansowanie_i_ubezpieczenia',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_finansowanie_i_ubezpieczenia',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_13_title',
							'label' => __('Volvo Personal Service', 'partners-site_v2'),
							'name' => 'department_13_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_13_name',
							'label' => __('Volvo Personal Service', 'partners-site_v2'),
							'name' => 'department_13_name',
							'type' => 'text',
							'default_value' => 'volvo_personal_service', 
						),
						array(
							'key' => 'field_department_hours_volvo_personal_service',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_volvo_personal_service',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_volvo_personal_service',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_volvo_personal_service',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_volvo_personal_service',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_volvo_personal_service',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_volvo_personal_service',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_volvo_personal_service',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_14_title',
							'label' => __('Reception', 'partners-site_v2'),
							'name' => 'department_14_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_14_name',
							'label' => __('Reception', 'partners-site_v2'),
							'name' => 'department_14_name',
							'type' => 'text',
							'default_value' => 'recepcja', 
						),
						array(
							'key' => 'field_department_hours_recepcja',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_recepcja',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_recepcja',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_recepcja',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_recepcja',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_recepcja',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_recepcja',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_recepcja',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_15_title',
							'label' => __('Administrative Office', 'partners-site_v2'),
							'name' => 'department_15_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_15_name',
							'label' => __('Administrative Office', 'partners-site_v2'),
							'name' => 'department_15_name',
							'type' => 'text',
							'default_value' => 'sekretariat', 
						),
						array(
							'key' => 'field_department_hours_sekretariat',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_sekretariat',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_sekretariat',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_sekretariat',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_sekretariat',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_sekretariat',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_sekretariat',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_sekretariat',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_16_title',
							'label' => __('Marketing and PR', 'partners-site_v2'),
							'name' => 'department_16_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_16_name',
							'label' => __('Marketing and PR', 'partners-site_v2'),
							'name' => 'department_16_name',
							'type' => 'text',
							'default_value' => 'marketing_i_pr', 
						),
						array(
							'key' => 'field_department_hours_marketing_i_pr',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_marketing_i_pr',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_marketing_i_pr',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_marketing_i_pr',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_marketing_i_pr',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_marketing_i_pr',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_marketing_i_pr',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_marketing_i_pr',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_17_title',
							'label' => __('Data Protection Officer', 'partners-site_v2'),
							'name' => 'department_17_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_17_name',
							'label' => __('Data Protection Officer', 'partners-site_v2'),
							'name' => 'department_17_name',
							'type' => 'text',
							'default_value' => 'inspektor_ochrony_danych_osobowych', 
						),
						array(
							'key' => 'field_department_hours_inspektor_ochrony_danych_osobowych',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_inspektor_ochrony_danych_osobowych',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_inspektor_ochrony_danych_osobowych',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_inspektor_ochrony_danych_osobowych',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_inspektor_ochrony_danych_osobowych',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_inspektor_ochrony_danych_osobowych',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_inspektor_ochrony_danych_osobowych',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_inspektor_ochrony_danych_osobowych',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_18_title',
							'label' => __('Human Resources', 'partners-site_v2'),
							'name' => 'department_18_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_18_name',
							'label' => __('Human Resources', 'partners-site_v2'),
							'name' => 'department_18_name',
							'type' => 'text',
							'default_value' => 'kadry', 
						),
						array(
							'key' => 'field_department_hours_kadry',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_kadry',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_kadry',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_kadry',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_kadry',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_kadry',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_kadry',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_kadry',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_19_title',
							'label' => __('Tourist & Diplomat Sales', 'partners-site_v2'),
							'name' => 'department_19_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_19_name',
							'label' => __('Tourist & Diplomat Sales', 'partners-site_v2'),
							'name' => 'department_19_name',
							'type' => 'text',
							'default_value' => 'tourist_&_diplomat_sales', 
						),
						array(
							'key' => 'field_department_hours_tourist_&_diplomat-sales',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_tourist_&_diplomat_sales',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_tourist_&_diplomat-sales',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_tourist_&_diplomat-sales',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_tourist_&_diplomat-sales',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_tourist_&_diplomat-sales',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_tourist_&_diplomat-sales',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_tourist_&_diplomat-sales',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_20_title',
							'label' => __('Accessories', 'partners-site_v2'),
							'name' => 'department_20_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_20_name',
							'label' => __('Accessories', 'partners-site_v2'),
							'name' => 'department_20_name',
							'type' => 'text',
							'default_value' => 'akcesoria', 
						),
						array(
							'key' => 'field_department_hours_akcesoria',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_akcesoria',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_akcesoria',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_akcesoria',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_akcesoria',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_akcesoria',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_akcesoria',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_akcesoria',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_department_21_title',
							'label' => __('Parts', 'partners-site_v2'),
							'name' => 'department_20_title',
							'type' => 'message',
						),
						array(
							'key' => 'field_department_21_name',
							'label' => __('Parts', 'partners-site_v2'),
							'name' => 'department_21_name',
							'type' => 'text',
							'default_value' => 'czesci', 
						),
						array(
							'key' => 'field_department_hours_czesci',
							'label' => __('Hours', 'partners-site_v2'),
							'name' => 'department_hours_czesci',
							'type' => 'group',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_week_hours_czesci',
									'label' => __('Monday - Friday', 'partners-site_v2'),
									'name' => 'week',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_week_open_czesci',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_week_close_czesci',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
								array(
									'key' => 'field_sat_hours_czesci',
									'label' => __('Saturday', 'partners-site_v2'),
									'name' => 'saturday',
									'type' => 'group',
									'layout' => 'row',
									'wrapper' => array('width' => 50), 
									'sub_fields' => array(
										array(
											'key' => 'field_sat_open_czesci',
											'label' => __('Opening time', 'partners-site_v2'),
											'name' => 'open',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
										array(
											'key' => 'field_sat_close_czesci',
											'label' => __('Closing time', 'partners-site_v2'),
											'name' => 'close',
											'type' => 'time_picker',
											'display_format' => 'H:i:s',
											'return_format' => 'H:i:s',
											'wrapper' => array('width' => 50),
										),
									),
								),
							),
						),
						
						
					),
				),
				
				
				
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'showroom',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'discussion',
				4  => 'comments',
				5  => 'slug',
				6  => 'author',
				7  => 'format',
				8  => 'page_attributes',
				9  => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
			'active'                => true,
			'description'           => '',
		)
	);
endif;
