<?php

use Classes\CarDictionary;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\GuzzleException;
$post_id = (isset($_GET['post']) ? $_GET['post'] : null);
$dictionary = new CarDictionary(new GuzzleHttp\Client());
if (function_exists('acf_add_local_field_group')):

	
	acf_add_local_field_group(
		array(
			'key' => 'group_602b8b955a3ee',
			'title' => __('StockCar', 'partners-site_v2'),
			'fields' => array(
				array(
					'key' => 'archive',
					'label' => __('Car in the archive', 'partners-site_v2'),
					'name' => 'archive',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_602b98e74c235',
					'label' => __('Basic data', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_60f9397eb3d12',
					'label' => __('Mark car as recommended', 'partners-site_v2'),
					'name' => 'is-featured',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),

				array(
					'key' => 'field_602b972302941',
					'label' => __('VIN', 'partners-site_v2'),
					'name' => 'vin',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_602b972302942',
					'label' => __('CON', 'partners-site_v2'),
					'name' => 'con',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_pno',
					'label' => __('PNO12', 'partners-site_v2'),
					'name' => 'pno',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => CarDictionary::getPno12(),
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'eurocode',
					'label' => __('Eurocode', 'partners-site_v2'),
					'name' => 'eurocode',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_car_type',
					'label' => __('Condition', 'partners-site_v2'),
					'name' => 'cartype',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'nowy' => __( 'new', 'partners-site_v2' ),
						'used' => __( 'used', 'partners-site_v2' ),
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				
				
				
				array(
					'key' => 'field_602b972302487',
					'label' => __('Offer No.', 'partners-site_v2'),
					'name' => 'offer-number',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_602b973702488',
					'label' => __('Salesperson\'s phone number', 'partners-site_v2'),
					'name' => 'sales-phone',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_602b976a02489',
					'label' => sprintf(__('Regular price (%s gross)', 'partners-site_v2'), __( 'currency', 'partners-site_v2' )),
					'name' => 'regular-price',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'omnibus_price',
					'label' => __('Omnibus price', 'partners-site_v2'),
					'name' => 'omnibus_price',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_602b97980248f',
					'label' => __('Has a promotional price', 'partners-site_v2'),
					'name' => 'has-discount-price',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_602b97980248a',
					'label' => sprintf(__( 'Cena promocyjna (%s brutto)', 'partners-site_v2' ), __( 'currency', 'partners-site_v2' )),
					'name' => 'discount-price',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_602b97980248f',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_602b97fd0248b',
					'label' => __('Year of manufacture', 'partners-site_v2'),
					'name' => 'production-year',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'car-distance',
					'label' => __('Mileage in kilometers', 'partners-site_v2'),
					'name' => 'car-distance',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_mileage',
					'label' => __('Mileage', 'partners-site_v2'),
					'name' => 'mileage',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'0-20000' => __( '0-20,000 km', 'partners-site_v2' ),
						'20001-100000' => __( '20,000-100,000 km', 'partners-site_v2' ),
						'100001-200000' => __( '20-100 tys. km', 'partners-site_v2' ),
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_602b97fd02454c',
					'label' => __('Available for pickup within...', 'partners-site_v2'),
					'name' => 'pickup-time',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Do odbioru w ciągu 2 tygodni' => __( 'Ready for pickup within 2 weeks', 'partners-site_v2' ),
						'Do odbioru już jutro' => __( 'Ready for pickup tomorrow', 'partners-site_v2' ),
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6034b4fa1e85g',
					'label' => __( 'Showroom', 'partners-site_v2' ),
					'name' => 'showroom',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'showroom',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'id',
					'ui' => 1,
					'multi-showroom-only' => true,
				),
				array(
					'key' => 'field_602b98cc4c234',
					'label' => __('Technical Specifications', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_602b9c5902ce8',
					'label' => __( 'Version', 'partners-site_v2' ),
					'name' => 'version',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getVersions(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b96dc02583',
					'label' => __( 'Category', 'partners-site_v2' ),
					'name' => 'category',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getModelCategories(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b96dc02486',
					'label' => __( 'Model', 'partners-site_v2' ),
					'name' => 'model',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50', 
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getModels(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b992e02ce6',
					'label' => __('Color', 'partners-site_v2'),
					'name' => 'color',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getColors(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b9baa02ce7',
					'label' => __('Engine', 'partners-site_v2'),
					'name' => 'engine',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getEngines(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b9cb202ce9',
					'label' => __('Upholstery', 'partners-site_v2'),
					'name' => 'inlay',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getInlays(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false 
				),
				array(
					'key' => 'field_602b9d1e02cea',
					'label' => __('Transmission', 'partners-site_v2'),
					'name' => 'gearbox',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => CarDictionary::getGearboxes(),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b9ee702cf2',
					'label' => __( 'Seats', 'partners-site_v2' ),
					'name' => 'seats',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b9d5802ceb',
					'label' => __('Maximum Power (HP)', 'partners-site_v2'),
					'name' => 'max-power-text',
					'type' => 'text',
					'instructions' => __('Car power; for hybrids, listed as e.g., 230+15. This field is displayed in the car’s technical specifications.', 'partners-site_v2'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_602b9d7d02cec',
					'label' => __('Total maximum power (HP)', 'partners-site_v2'),
					'name' => 'max-power',
					'type' => 'number',
					'instructions' => __('Total vehicle power; this field is used to filter vehicles available immediately', 'partners-site_v2'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_602b9db802ced',
					'label' => __('Fuel Type', 'partners-site_v2'),
					'name' => 'fuel-type',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Diesel' => __( 'Diesel', 'partners-site_v2' ),
						'Benzyna' => __( 'Gasoline', 'partners-site_v2' ),
						'Hybryda Plug-In' => __( 'Plug-in hybrid', 'partners-site_v2' ),
						'Elektryczny' => __( 'Electric', 'partners-site_v2' ),

					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_602b9db802ced_drive',
					'label' => __('Drivetrain', 'partners-site_v2'),
					'name' => 'driveType',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'fwd' => __( 'Front-wheel drive (FWD)', 'partners-site_v2' ),
						'rwd' => __( 'Rear-wheel drive (RWD)', 'partners-site_v2' ),
						'4x4' => __( 'All-wheel drive (AWD)', 'partners-site_v2' ),
					),
					'default_value' => '',
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_602b9ddd02cee',
					'label' => __('Acceleration time (s)', 'partners-site_v2'),
					'name' => 'acceleration',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_602b97fd02454d',
					'label' => __('Engine type', 'partners-site_v2'),
					'name' => 'fuel-consumption-unit',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'l/100km' => __( 'l/100 km', 'partners-site_v2' ),
						'kWh/100km' => __( 'kWh/100 km', 'partners-site_v2' ),
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_602b9e2902cef',
					'label' => __('Average fuel consumption', 'partners-site_v2'),
					'name' => 'fuel-consumption',
					'type' => 'text',
					'instructions' => sprintf(__( '(max. %s chars)', 'partners-site_v2' ), 5),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '10',
					'replace_dot_with_comma' => true,
				),
				array(
					'key' => 'field_602b9e9102cf0',
					'label' => __( 'Maximum speed (km/h)', 'partners-site_v2' ),
					'name' => 'max-speed',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_erange',
					'label' => __('Electric range', 'partners-site_v2'),
					'name' => 'erange',
					'type' => 'number',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_602b9eb802cf1',
					'label' => __( 'Trunk capacity (liters)', 'partners-site_v2' ),
					'name' => 'cargo-capacity',
					'type' => 'number',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				

				array(
					'key' => 'field_602ba0d52720d',
					'label' => __('Photos', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'picture_format',
					'label' => __('Photo format 4:3', 'partners-site_v2'),
					'name' => 'picture_format',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					
					'default_value' => 0,
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'admin-only' => false
				),
				array(
					'key' => 'field_602ba0b52720c',
					'label' => __('Photos', 'partners-site_v2'),
					'name' => 'images',
					'type' => 'gallery',
					'instructions' => __('(min. width: 944px, Recommended width: 2877px)<br>(min. height: 453px)<br>When opened, the gallery displays the original photo size.', 'partners-site_v2'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'value',
					'preview_size' => 'medium',
					'insert' => 'append',
					'library' => 'all',
					'min' => '1',
					'max' => '',
					'min_width' => 808,
					'min_height' => 453,
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'social_image',
					'label' => __('Photo for product feeds', 'partners-site_v2'),
					'name' => 'social_image',
					'type' => 'gallery',
					'instructions' => __('(min. width: 944px, Recommended width: 2877px)<br>(min. height: 453px)<br>When opened, the gallery displays the original photo size.', 'partners-site_v2'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'integer',
					'preview_size' => 'medium',
					'insert' => 'append',
					'library' => 'all',
					'min' => '',
					'max' => '1',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6033bfb3737ec',
					'label' => __('Detailed technical specifications', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6033bfbe737ed',
					'label' => __( 'Header', 'partners-site_v2' ),
					'name' => 'accordion-heading',
					'type' => 'text',
					'instructions' => __( 'Domyślnie tekst nagłówka jest w kolorze szarym. <br>Aby dana fraza była w kolorze czarnym, proszę umieścić ją pomiędzy &lt;strong>&lt;/strong&gt; , np. &lt;strong>TEKST&lt;/strong&gt; <br>(max. 166 znaki)', 'partners-site_v2' ),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => 166,
				),
				array(
					'key' => 'field_60ffe8e3d4294',
					'label' => __('Detailed technical specifications', 'partners-site_v2'),
					'name' => 'accordion',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_60ffe933d4297',
							'label' => __('Section name', 'partners-site_v2'),
							'name' => 'name',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_60ffe93cd4298',
							'label' => __('Elements', 'partners-site_v2'),
							'name' => 'items',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_60ffe95cd4299',
									'label' => __('Element', 'partners-site_v2'),
									'name' => 'name',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
				),
				array(
					'key' => 'leasing_field',
					'label' => __('Financing', 'partners-site_v2'),
					'name' => 'leasing_field',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					// 'conditional_logic' => array(
					// 	array(
					// 		array(
					// 			'field' => 'field_car_type',
					// 			'operator' => '==',
					// 			'value' => 'nowy',
					// 		),
					// 	),
					// ),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'lease_car',
					'label' => __('Leasing offer', 'partners-site_v2'),
					'name' => 'lease_car',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					// 'conditional_logic' => array(
					// 	array(
					// 		array(
					// 			'field' => 'field_car_type',
					// 			'operator' => '==',
					// 			'value' => 'nowy',
					// 		),
					// 	),
					// ),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => $dictionary->filterLeaseOffer($post_id),
					'default_value' => $dictionary->getDefaultValue($post_id,'leasing'),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'najem_car',
					'label' => __('Rental offer', 'partners-site_v2'),
					'name' => 'najem_car',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					// 'conditional_logic' => array(
					// 	array(
					// 		array(
					// 			'field' => 'field_car_type',
					// 			'operator' => '==',
					// 			'value' => 'nowy',
					// 		),
					// 	),
					// ),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => $dictionary->filterNajemOffer($post_id),
					'default_value' => $dictionary->getDefaultValue($post_id,'najem'),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'income',
					'label' => __('Attractiveness/commission - Leasing', 'partners-site_v2'),
					'name' => 'income',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'lease_car',
								'operator' => '!=',
								'value' => 'none',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => $dictionary->getAttractionSettings( 'leasing' ),
					'default_value' => $dictionary->getAttractionDefault('leasing'),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'income_najem',
					'label' => __('Attractiveness/commission - Rental', 'partners-site_v2'),
					'name' => 'income_najem',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					// 'conditional_logic' => array(
					// 	array(
					// 		array(
					// 			'field' => 'field_car_type',
					// 			'operator' => '==',
					// 			'value' => 'nowy',
					// 		),
					// 	),
					// ),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'conditional_logic' => array(
						array(
							array(
								'field' => 'najem_car',
								'operator' => '!=',
								'value' => 0,
							),
						),
					),
					'choices' => $dictionary->getAttractionSettings( 'najem' ),
					'default_value' => $dictionary->getAttractionDefault('najem'),
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6033bfb37594d',
					'label' => __('Photos under detailed technical specifications', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6034b4fa1e81e',
					'label' => __('Photos under detailed technical specifications', 'partners-site_v2'),
					'name' => 'gallery',
					'type' => 'gallery',
					'instructions' => __('(3 photos required)<br>The gallery displays the original photo size when opened.', 'partners-site_v2'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'integer',
					'preview_size' => 'medium',
					'insert' => 'append',
					'library' => 'all',
					'min' => 0,
					'max' => 3,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'admin-only' => false
				),
				array(
					'key' => 'field_6101ae2e80539',
					'label' => __('Energy labels', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'activemotors',
								'operator' => '==',
								'value' => '0',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_6101ae3d8053a',
					'label' => __('Summer tires', 'partners-site_v2'),
					'name' => 'summer-tyre-labels',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_6101ae678053b',
							'label' => __('URL', 'partners-site_v2'),
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_6101ae728053c',
					'label' => __('Winter tires', 'partners-site_v2'),
					'name' => 'winter-tyre-labels',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_6101ae728053d',
							'label' => __('URL', 'partners-site_v2'),
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_stock_admin',
					'label' => __('Admin settings', 'partners-site_v2'),
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
					'admin-only' => true
				),
				array(
					'key' => 'odreki_sync',
					'label' => __('Synchronization odreki', 'partners-site_v2'),
					'name' => 'odreki_sync',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => __( 'No', 'partners-site_v2' ),
						1 => __( 'Yes', 'partners-site_v2' ),		
						2 => __( 'Waiting to be synchronized', 'partners-site_v2' )
					),
					'default_value' => 0,
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'admin-only' => true
				),
				array(
					'key' => 'activemotors',
					'label' => __('Car from Active Motors', 'partners-site_v2'),
					'name' => 'activemotors',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => __( 'No', 'partners-site_v2' ),
						1 => __( 'Yes', 'partners-site_v2' ),						
					),
					'default_value' => 0,
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'admin-only' => true
				),
				array(
					'key' => 'field_669a2a444fc5f',
					'label' => __('DOL Sync', 'partners-site_v2'),
					'name' => 'dol_sync',
					'aria-label' => '',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => __( 'Status not checked', 'partners-site_v2' ),
						1 => __( 'Data available in DOL', 'partners-site_v2' ),
						2 => __( 'Data not available in DOL', 'partners-site_v2' ),
						3 => __( 'DOL Synchronized', 'partners-site_v2' ),
						4 => __( 'Synchronization failed', 'partners-site_v2' ),
					),
					'default_value' => 0,
					'return_format' => 'value',
					'allow_null' => 0,
					'other_choice' => 0,
					'layout' => 'vertical',
					'save_other_choice' => 0,
					'admin-only' => true
				),
				array(
					'key' => 'model_1',
					'label' => __( 'Model', 'partners-site_v2' ),
					'name' => 'model_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'version_1',
					'label' => __( 'Version', 'partners-site_v2' ),
					'name' => 'version_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'color_1',
					'label' => __('Color', 'partners-site_v2'),
					'name' => 'color_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'inlay_1',
					'label' => __('Upholstery', 'partners-site_v2'),
					'name' => 'inlay_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'engine_1',
					'label' => __('Engine', 'partners-site_v2'),
					'name' => 'engine_1',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'field_602b9efc02cf3',
					'label' => __( 'Height (cm)', 'partners-site_v2' ),
					'name' => 'height',
					'type' => 'number',
					'instructions' => '<strong>' . __( 'NOTE! The value must be entered in centimeters', 'partners-site_v2' ) . '</strong>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'field_602b9f0c02cf4',
					'label' => __( 'Length (cm)', 'partners-site_v2' ),
					'name' => 'length',
					'type' => 'number',
					'instructions' => '<strong>' . __( 'NOTE! The value must be entered in centimeters', 'partners-site_v2' ) . '</strong>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),
				array(
					'key' => 'field_602b9f1e02cf5',
					'label' => __( 'Width with mirrors (cm)', 'partners-site_v2' ),
					'name' => 'width',
					'type' => 'number',
					'instructions' => '<strong>' . __( 'NOTE! The value must be entered in centimeters', 'partners-site_v2' ) . '</strong>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'admin-only' => true
				),
				array(
					'key' => 'field_602b9f2f02cf6',
					'label' => __( 'Ground clearance (cm)', 'partners-site_v2' ),
					'name' => 'ground-clearance',
					'type' => 'number',
					'instructions' => '<strong>' . __( 'NOTE! The value must be entered in centimeters', 'partners-site_v2' ) . '</strong>',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'admin-only' => true
				),

			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'stock-car',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		)
	);


endif;

add_action('acf/save_post', 'updateStockCarDiscountPrice');
function updateStockCarDiscountPrice($postId)
{
	if (get_post_type($postId) !== 'stock-car') {
		return;
	}

	$hasDiscountPrice = get_field('has-discount-price', $postId);

	if (!$hasDiscountPrice) {
		$regularPrice = get_field('regular-price', $postId);

		update_field('discount-price', $regularPrice, $postId);
	}
}
