<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'threeBoxWidzet',
			'title'                 => 'Trzy boksy',
			'fields'                => array(
				array(
					'key'               => 'mainTitleBox',
					'label'             => 'Naglowek',
					'name'              => 'mainHeading',
					'type'              => 'text',
					'instructions' => __( 'Domyślnie tekst jest koloru ciemnego, jeżeli jakaś część ma być wyróżniona na szaro, należy ją otoczyć tagami <strong></strong>.', 'partners-site_v2' ),
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),

				array(
					'key'               => 'offerThreeBox1',
					'label'             => 'Box 1',
					'name'              => 'offerBox1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => true,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox',
							'label' => __( 'Zdjęcie', 'partners-site_v2' ),
							'name'              => 'imageBox',
							'type'              => 'image',
							'instructions' => __( 'Dodaj zdjęcie', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox',
							'label' => __( 'Tytuł', 'partners-site_v2' ),
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox2',
					'label'             => 'Box 2',
					'name'              => 'offerBox2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => true,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox2',
							'label' => __( 'Zdjęcie', 'partners-site_v2' ),
							'name'              => 'imageBox2',
							'type'              => 'image',
							'instructions' => __( 'Dodaj zdjęcie', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox2',
							'label' => __( 'Tytuł', 'partners-site_v2' ),
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox2',
							'label'             => 'Opis',
							'name'              => 'description2',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox2',
							'label'             => 'Link',
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox3',
					'label'             => 'Box 3',
					'name'              => 'offerBox3',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => true,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox3',
							'label' => __( 'Zdjęcie', 'partners-site_v2' ),
							'name'              => 'imageBox3',
							'type'              => 'image',
							'instructions' => __( 'Dodaj zdjęcie', 'partners-site_v2' ),
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox3',
							'label' => __( 'Tytuł', 'partners-site_v2' ),
							'name'              => 'heading3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox3',
							'label'             => 'Opis',
							'name'              => 'description3',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox3',
							'label'             => 'Link',
							'name'              => 'link3',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/three-boxes',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

endif;
