<?php


if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_603cee7231e0c',
        'title' => __('TwoColumnContentComponent', 'partners-site_v2'),
        'fields' => array(
            array(
                'key' => 'field_603cee7eb259a',
                'label' => __( 'Photo', 'partners-site_v2' ),
                'name' => 'img',
                'type' => 'image',
                'instructions' => __('Please ensure that the content height does not exceed the image height<br>(min. width 959px, Recommended width: 2877px)', 'partners-site_v2'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'integer',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_603ceef6167bd',
                'label' => __('Video', 'partners-site_v2'),
                'name' => 'video',
                'type' => 'text',
                'instructions' => __( 'Link to the video on youtube.com<br> e.g., https://www.youtube.com/watch?v=LXb3EKWsInQ&t=4s', 'partners-site_v2' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_6074604797816',
                'label' => __('Image width', 'partners-site_v2'),
                'name' => 'image-width',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    50 => '1/2',
                    70 => '2/3',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 70,
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_6074609197817',
                'label' => __('Image position', 'partners-site_v2'),
                'name' => 'image-position',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => __( 'Left', 'partners-site_v2' ),
                    'right' => __( 'Right', 'partners-site_v2' ),
                    'offline' => __( 'Hide the photo', 'partners-site_v2' ),
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'left',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_603ceec1b259c',
                'label' => __( 'Subtitle', 'partners-site_v2' ),
                'name' => 'subheading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key'               => 'headingTag',
                'label'             => __('Header type', 'partners-site_v2'),
                'name'              => 'heading_tag',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'choices' => array(
                    'h1' => 'H1',
                    'h2' => 'H2',
                    'h3' => 'H3',
                    'h4' => 'H4',
                    'h5' => 'H5',
                    'h6' => 'H6',
                ),
                'default_value' => 'h2',
                'allow_null'    => 0,
                'multiple'      => 0,
                'ui'            => 0, 
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_603ceec9b259d',
                'label' => __( 'Header', 'partners-site_v2' ),
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'single_opt_column',
                'label' => __('Single-column content (left)', 'partners-site_v2'),
                'name' => 'single_opt_column',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => [
                    'single_opt_properties' => array(
                        'key' => 'single_opt_property',
                        'name' => 'list',
                        'label' => __('List of benefits', 'partners-site_v2'),
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'single_opt_property',
                                'label' => __('List of benefits', 'partners-site_v2'),
                                'name' => 'single_opt_property',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'single_property_value',
                                        'label' => __('Value', 'partners-site_v2'),
                                        'name' => 'single_property_value',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'single_property_label',
                                        'label' => __('Unit', 'partners-site_v2'),
                                        'name' => 'single_property_label',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'single_property_desc',
                                        'label' => __('Additional text', 'partners-site_v2'),
                                        'name' => 'single_property_desc',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ],
                'button_label' => __( 'Add Content', 'partners-site_v2' ),
                'min' => '',
                'max' => '',
            ),
            array(
                'key' => 'field_605de527d4054',
                'label' => __('Single-column content', 'partners-site_v2'),
                'name' => 'content',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array( 
                    'layout_new_title' => array(
                    'key' => 'layout_new_title',
                    'name' => 'title',
                    'label' => __( 'Title', 'partners-site_v2' ),
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_title',
                            'label' => __( 'Title', 'partners-site_v2' ),
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                    'layout_605de535462fa' => array(
                        'key' => 'layout_605de535462fa',
                        'name' => 'description',
                        'label' => __( 'Description', 'partners-site_v2' ),
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de542d4055',
                                'label' => __( 'Description', 'partners-site_v2' ),
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de54bd4056' => array(
                        'key' => 'layout_605de54bd4056',
                        'name' => 'contact-info',
                        'label' => __( 'Contact person', 'partners-site_v2' ),
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de569d4057',
                                'label' => __( 'Contact person', 'partners-site_v2' ),
                                'name' => 'contact-info',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'employee',
                                ),
                                'taxonomy' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'id',
                                'ui' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de587d4058' => array(
                        'key' => 'layout_605de587d4058',
                        'name' => 'list',
                        'label' => __('List of benefits', 'partners-site_v2'),
                        'display' => 'block',
                        'sub_fields' => array(

                            array(
                                'key' => 'listView',
                                'label' => __('List view', 'partners-site_v2'),
                                'name' => 'listView',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    '1column' => __( '1 column', 'partners-site_v2' ),
                                    '2column' => __( '2 columns', 'partners-site_v2' ),
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '2column',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                            
                            array(
                                'key' => 'field_605de5a1d4059',
                                'label' => __('List of benefits', 'partners-site_v2'),
                                'name' => 'list',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_605de5acd405a',
                                        'label' => __('Text', 'partners-site_v2'),
                                        'name' => 'text',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de5b2d405b' => array(
                        'key' => 'layout_605de5b2d405b',
                        'name' => 'link',
                        'label' => __( 'Button', 'partners-site_v2' ),
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de5c1d405d',
                                'label' => __( 'Button action', 'partners-site_v2' ),
                                'name' => 'buttonAction',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'link' => __('Link', 'partners-site_v2'),
                                    'form' => __( 'Form', 'partners-site_v2' ),
                                ],
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_605de5c1d405e',
                                'label' => __( 'Button Text', 'partners-site_v2' ),
                                'name' => 'buttonText',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_605de5c1d405d',
                                            'operator' => '==',
                                            'value' => 'form',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'button_label' => __( 'Add Content', 'partners-site_v2' ),
                                'min' => '',
                                'max' => '', 'maxlength' => 30,
                            ),
                            array(
                                'key' => 'field_605de5c1d405c',
                                'label' => __('Link', 'partners-site_v2'),
                                'name' => 'link',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_605de5c1d405d',
                                            'operator' => '==',
                                            'value' => 'link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de5d5d405d' => array(
                        'key' => 'layout_605de5d5d405d',
                        'name' => 'table',
                        'label' => __( 'Table', 'partners-site_v2' ),
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de5dbd405e',
                                'label' => __( 'Table', 'partners-site_v2' ),
                                'name' => 'table',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_605de5e4d405f',
                                        'label' => __('Label', 'partners-site_v2'),
                                        'name' => 'label',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_605de65fd4060',
                                        'label' => __('Value', 'partners-site_v2'),
                                        'name' => 'value',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
						'layout_price_from' => array(
							'key' => 'layout_price_from',
							'name' => 'price_from',
							'label' => __('Price from', 'partners-site_v2'),
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'price_from_group',
									'label' => __('Price from', 'partners-site_v2'),
									'name' => 'price_from_group',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 1,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'price_from_text',
											'label' => __('Text', 'partners-site_v2'),
											'name' => 'price_from_text',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => 10,
										),
										array(
											'key' => 'field_price',
											'label' => __('Price', 'partners-site_v2'),
											'name' => 'field_price',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => 20,
										),
									),
								),
							),
							'min' => '',
							'max' => 1,
						),
                ),
                'button_label' => __( 'Add Content', 'partners-site_v2' ),
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/two-column-content-component',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
