<?php

use Classes\IconsDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) {
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6040abef6f8e7',
			'title'                 => 'Pola opcji strony głównej',
			'fields'                => array( 
				// Główny Slider
				array(
					'key'               => 'field_6040ae9e41086',
					'label'             => 'Główny Slider',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'field_6040b1f2a66b3',
					'label'             => 'Główny Slider',
					'name'              => 'slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040aed641087',
							'label'             => 'Kampanie wyświetlane na sliderze',
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => '(max. 3 kampanie)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => 'Dodaj kampanię',
							'sub_fields'        => array(
								array(
									'key'               => 'field_605f5e7850fbe',
									'label'             => 'Typ kampanii',
									'name'              => 'type',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'local'  => 'Kampania lokalna',
										'global' => 'Kampania globalna',
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_605f5ea150fbf',
									'label'             => 'Kampania',
									'name'              => 'local-campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_605f5e7850fbe',
												'operator' => '==',
												'value'    => 'local',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key'               => 'field_605f5ec150fc0',
									'label'             => 'Kampania',
									'name'              => 'global-campaign',
									'type'              => 'network_post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_605f5e7850fbe',
												'operator' => '==',
												'value'    => 'global',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key' => 'hide_campaign',
									'label' => 'Zastąp kampanie',
									'name' => 'hide_campaign',
									'type' => 'network_post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_605f5e7850fbe',
												'operator' => '==',
												'value' => 'global',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => array(
										0 => 'campaign',
									),
									'taxonomy' => '',
									'allow_null' => 0,
									'multiple' => 0,
									'admin-only' => false,
									'return_format' => 'id',
									'ui' => 1,
								)
							),
						),
					),
				),

				// Oferta specjalna
				array(
					'key'               => 'specialOffer',
					'label'             => 'Oferta specjalna',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'onOffOffer',
					'label'             => 'Czy oferta ma się wyświetlić?',
					'name'              => 'offerBtn',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'specialOfferTitle',
					'label'             => 'opis',
					'name'              => 'offerTitle',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),
				array(
					'key'               => 'offerLinks',
					'label'             => 'Link',
					'name'              => 'offerLinks',
					'type'              => 'link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '60',
				),
				

				
				


				// szare boksy 
				array(
					'key'               => 'greyBox',
					'label'             => 'Szare boksy',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),

				array(
					'key'               => 'greyBox1',
					'label'             => 'Box 1',
					'name'              => 'greyBox1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle',
							'label'             => 'Tytuł',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox2',
					'label'             => 'Box 2',
					'name'              => 'greyBox2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle2',
							'label'             => 'Tytuł',
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription2',
							'label'             => 'Opis',
							'name'              => 'description2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox2',
							'label'             => 'Link',
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox3',
					'label'             => 'Box 3',
					'name'              => 'greyBox3',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle3',
							'label'             => 'Tytuł',
							'name'              => 'heading3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription3',
							'label'             => 'Opis',
							'name'              => 'description3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox3',
							'label'             => 'Link',
							'name'              => 'link3',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'greyBox4',
					'label'             => 'Box 4',
					'name'              => 'greyBox4',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,  
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'table',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						
						array(
							'key'               => 'greyBoxTitle4',
							'label'             => 'Tytuł',
							'name'              => 'heading4',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '25',

						),
						array(
							'key'               => 'greyBoxDescription4',
							'label'             => 'Opis',
							'name'              => 'description4',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '120',
						),
						array(
							'key'               => 'greyLinksBox4',
							'label'             => 'Link',
							'name'              => 'link4',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				

				// Sprzedaż
				array(
					'key'               => 'field_6040b1d2a66b2',
					'label'             => 'Sprzedaż',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'field_6040b0e9a66af',
					'label'             => 'Sprzedaż',
					'name'              => 'offers',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'admin-only'        => true,
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040b0fca66b0',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => 'Domyślnie tekst nagłówka jest w kolorze szarym. Aby dana fraza była w kolorze czarnym, proszę umieścić ją pomiędzy &lt;strong>&lt;/strong&gt; , np. &lt;strong>TEKST&lt;/strong&gt;',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'child-site-only'   => false,
						),
						array(
							'key'               => 'field_6042225721aa6',
							'label'             => 'Włącz Preview Component',
							'name'              => 'enable-preview-component',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 1,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_6040b24ea66b4',
							'label'             => 'Preview Component',
							'name'              => 'preview-component',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_6042225721aa6',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'child-site-only'   => false,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b3a6a66b5',
									'label'             => 'Zdjęcie',
									'name'              => 'image',
									'type'              => 'image',
									'instructions'      => '(min. szerokość: 944px, Zalecana szerokość: 2832px)',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'integer',
									'preview_size'      => 'medium',
									'library'           => 'all',
									'min_width'         => 612,
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								
								array(
									'key'               => 'field_6040b40ba66b7',
									'label'             => 'Nagłówek',
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_6040b41ba66b8',
									'label'             => 'Opis',
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => '',
									'rows'              => '',
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_6040b435a66b9',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
						),
						array(
							'key'               => 'field_6040b4b5a66ba',
							'label'             => 'Kafelki sprzedażowe',
							'name'              => 'offer-boxes',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'admin-only'        => false,
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b4cea66bb',
									'label'             => 'Elementy',
									'name'              => 'items',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 3,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6040b4f3a66bc',
											'label'        => 'Ikona',
											'name'         => 'icon',
											'type'         => 'icon_select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => IconsDictionary::getIcons(),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'value',
											'ui'           => 1,
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'field_6040b51ca66bd',
											'label'        => 'Nagłówek',
											'name'         => 'heading',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
										),
										array(
											'key'          => 'field_6040b523a66be',
											'label'        => 'Opis',
											'name'         => 'description',
											'type'         => 'textarea',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'maxlength'    => '',
											'rows'         => '',
											'new_lines'    => '',
										),
										array(
											'key'          => 'field_6040b53ea66bf',
											'label'        => 'Link',
											'name'         => 'link',
											'type'         => 'link',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'return_format' => 'array',
										),
									),
								),
							),
						),
					),
				),
				// oferta 2 karty
				array(
					'key'               => 'offerTwoCards',
					'label'             => 'Oferta dwie karty',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'offerFirstCard',
					'label'             => 'Oferta karta 1',
					'name'              => 'offer1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageCard',
							'label'             => 'Zdjęcie',
							'name'              => 'imageCard',
							'type'              => 'image',
							'instructions'      => 'Dodaj zdjęcie dla karty.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						

						array(
							'key'               => 'choiceInput',
							'label'             => 'Wybierz opcję',
							'name'              => 'select_option',
							'type'              => 'select',
							'instructions'      => 'Wybierz jedną z dostępnych opcji.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'gwarancja'    => 'Gwarancja',
								'bezpieczenstwo' => 'Bezpieczeństwo',
								'akcesoria' => 'Akcesoria',
								'oferta'	=> 'Oferta',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
						

						array(
							'key'               => 'titleCard',
							'label'             => 'Tytuł karty',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionCard',
							'label'             => 'Opis',
							'name'              => 'descriptionCard',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksCard',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerSecondCard',
					'label'             => 'Oferta karta 2',
					'name'              => 'offer2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageCard2',
							'label'             => 'Zdjęcie',
							'name'              => 'imageCard2',
							'type'              => 'image',
							'instructions'      => 'Dodaj zdjęcie dla karty.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						

						array(
							'key'               => 'choiceInput2',
							'label'             => 'Wybierz opcję',
							'name'              => 'select_option2',
							'type'              => 'select',
							'instructions'      => 'Wybierz jedną z dostępnych opcji.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'gwarancja'    => 'Gwarancja',
								'bezpieczenstwo' => 'Bezpieczeństwo',
								'akcesoria'		 => 'Akcesoria',
								'oferta'		 => 'Oferta',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'value',
							'placeholder'       => '',
						),
						

						array(
							'key'               => 'titleCard2',
							'label'             => 'Tytuł karty',
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionCard2',
							'label'             => 'Opis',
							'name'              => 'descriptionCard2',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
							'new_lines'         => '',
						),
						array(
							'key'               => 'linksCard2',
							'label'             => 'Link',
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),

				// slider Rodzina
				array(
					'key'               => 'sliderFamily',
					'label'             => 'rodzina Volvo',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array( 
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'sliderTitle',
					'label'             => 'Nagłówek',
					'name'              => 'sliderTitle',
					'type'              => 'text',
					'instructions'      => 'Aby nadać tekstowi kolor szary, umieść go pomiędzy znacznikami <strong></strong>',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),
				array(
					'key'               => 'sliderFamilyBox',
					'label'             => 'Slider Rodzina Volvo',
					'name'              => 'sliderFamilyBox',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'choiceFamily',
							'label'             => 'Wybierz opcję',
							'name'              => 'choiceFamily',
							'type'              => 'select',
							'instructions'      => 'Wybierz jedną z dostępnych opcji.',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'suv'    => 'SUV',
								'sedan' => 'Sedan',
								'kombi'    => 'Kombi',
								'electric' => 'Elektryczne',
							
		
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'ajax'              => 0,
							'return_format'     => 'label',
							'placeholder'       => '',
						),

						array(
							'key'               => 'imageslider',
							'label'             => 'Zdjęcie',
							'name'              => 'imageSlider',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
					
						array(
							'key'               => 'nameCar',
							'label'             => 'Model Volvo',
							'name'              => 'nameCar',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'priceCar',
							'label'             => 'Cena samochodu',
							'name'              => 'priceCar',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksSlide',
							'label'             => 'Link',
							'name'              => 'linksSlide',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				
				// oferta 3 boksy
				array(
					'key'               => 'offerThreeBox',
					'label'             => 'Oferta trzy boxy',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),

				array(
					'key'               => 'mainTitleBox',
					'label'             => 'Naglowek',
					'name'              => 'mainHeading',
					'type'              => 'text',
					'instructions'      => 'Domyślnie tekst jest koloru ciemnego, jeżeli jakaś część ma być wyróżniona na szaro, należy ją otoczyć tagami <strong></strong>.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',

				),

				array(
					'key'               => 'offerThreeBox1',
					'label'             => 'Box 1',
					'name'              => 'offerBox1',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox',
							'label'             => 'Zdjęcie',
							'name'              => 'imageBox',
							'type'              => 'image',
							'instructions'      => 'Dodaj zdjęcie',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox',
							'label'             => 'Tytuł',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox2',
					'label'             => 'Box 2',
					'name'              => 'offerBox2',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox2',
							'label'             => 'Zdjęcie',
							'name'              => 'imageBox2',
							'type'              => 'image',
							'instructions'      => 'Dodaj zdjęcie',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox2',
							'label'             => 'Tytuł',
							'name'              => 'heading2',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox2',
							'label'             => 'Opis',
							'name'              => 'description2',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox2',
							'label'             => 'Link',
							'name'              => 'link2',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				array(
					'key'               => 'offerThreeBox3',
					'label'             => 'Box 3',
					'name'              => 'offerBox3',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(

						array(
							'key'               => 'imageBox3',
							'label'             => 'Zdjęcie',
							'name'              => 'imageBox3',
							'type'              => 'image',
							'instructions'      => 'Dodaj zdjęcie',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array', 
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '', 
						),
						array(
							'key'               => 'titleBox3',
							'label'             => 'Tytuł',
							'name'              => 'heading3',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'descriptionBox3',
							'label'             => 'Opis',
							'name'              => 'description3',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 100,
						),
						array(
							'key'               => 'linksBox3',
							'label'             => 'Link',
							'name'              => 'link3',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
						
					),
				),
				

				//  Oferta
				array(
					'key'               => 'offerCardTab',
					'label'             => 'Oferta',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => false,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'OfferCard',
					'label'             => 'Oferta',
					'name'              => 'OfferCard',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'admin-only'        => false,
					'child-site-only'   => false,
					'sub_fields'        => array(
						array(
							'key'               => 'imageOffer',
							'label'             => 'Zdjęcie',
							'name'              => 'image',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format' => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
						array(
							'key'               => 'headingOffer',
							'label'             => 'Nagłówek',
							'name'              => 'headingOffer',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'child-site-only'   => false,
						),
						array(
							'key'               => 'descriptionOffer',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'linkOffer',
							'label'             => 'Link',
							'name'              => 'link',
							'type'              => 'link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
						),
					),
				),

				// Dostępne na miejscu
				array(
					'key'               => 'field_6040b56fa66c0',
					'label'             => 'Dostępne na miejscu',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => true,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'field_6040b579a66c1',
					'label'             => 'Dostępne na miejscu',
					'name'              => 'stock-cars',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => false,
					'admin-only'        => false,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6040b58aa66c2',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => 'Domyślnie tekst nagłówka jest w kolorze szarym. Aby dana fraza była w kolorze czarnym, proszę umieścić ją pomiędzy &lt;strong>&lt;/strong&gt; , np. &lt;strong>TEKST&lt;/strong&gt;',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',

						),
						array(
							'key'               => 'field_6040b479a66c1',
							'label'             => 'Zajawka',
							'name'              => 'excerpt',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'block',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6040b58aa66c3',
									'label'             => 'Nagłówek',
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 30,
								),
								array(
									'key'               => 'field_6040b58aa66c4',
									'label'             => 'Opis',
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 100,
								),
								array(
									'key'               => 'field_6040b435a66a0',
									'label'             => 'Link',
									'name'              => 'link',
									'type'              => 'link',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'array',
								),
							),
						),
					),
				),
				// Zdjęcie na dole strony głównej
				array(
					'key'               => 'field_6040b5b9a66c4',
					'label'             => 'Zdjęcie na dole strony głównej',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'admin-only'        => true,
					'endpoint'          => 0,
					'child-site-only'   => false,
				),
				array(
					'key'               => 'mobile_homepage_image',
					'label'             => 'Zdjęcie mobile',
					'name'              => 'mobile_homepage_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 612,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_6040b5d5a66c5',
					'label'             => 'Zdjęcie na dole strony głównej',
					'name'              => 'bottom-image',
					'type'              => 'image',
					'instructions'      => '(min. szerokość: 1920px, Zalecana szerokość: 3840px)',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'admin-only'        => false,
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 1280,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
					'child-site-only'   => false,
				),
				array(
					'key'               => 'mobile_homepage_image',
					'label'             => 'Zdjęcie mobile',
					'name'              => 'mobile_homepage_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'integer',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => 612,
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'options-homepage',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
}

add_filter( 'acf/fields/relationship/query/key=field_6040aed641087', 'modifyHomepageSliderItemsQuery', 10, 3 );
function modifyHomepageSliderItemsQuery( $args, $field, $post_id ): array {
	$args['network']   = true;
	$args['sites__in'] = array( 1, get_current_blog_id() );
	return $args;
}

add_filter( 'acf/fields/relationship/result', 'modifyHomepageSliderItemsResult', 10, 4 );
function modifyHomepageSliderItemsResult( $text, $post ): string {
	if ( get_current_blog_id() !== 1 && $post->site_ID == 1 ) {
		return '[Globalna] ' . $text;
	}
	return $text;
}
