<?php

use Classes\IconsDictionary;

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6062210c411fe',
			'title'                 => 'Serwis',
			'fields'                => array(
				array(
					'key'               => 'field_606222183bd26',
					'label'             => 'Slider',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_606222213bd27',
					'label'             => 'Slider',
					'name'              => 'service-slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'child-site-only'   => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606222353bd28',
							'label'             => 'Kampanie wyświetlane na sliderze',
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => 'Dodaj kampanię',
							'sub_fields'        => array(
								array(
									'key'               => 'field_606222543bd29',
									'label'             => 'Typ kampanii',
									'name'              => 'type',
									'type'              => 'select',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => array(
										'local'  => 'Kampania lokalna',
										'global' => 'Kampania globalna',
									),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 0,
									'return_format'     => 'value',
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_606222863bd2a',
									'label'             => 'Kampania',
									'name'              => 'local-campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_606222543bd29',
												'operator' => '==',
												'value'    => 'local',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
								array(
									'key'               => 'field_606222ac3bd2b',
									'label'             => 'Kampania',
									'name'              => 'global-campaign',
									'type'              => 'network_post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_606222543bd29',
												'operator' => '==',
												'value'    => 'global',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606222213bd273',
					'label'             => 'Slider',
					'name'              => 'global-service-slider',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606222213bd274',
							'label'             => 'Kampanie wyświetlane na sliderze',
							'name'              => 'slides',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'row',
							'button_label'      => 'Dodaj kampanię',
							'sub_fields'        => array(
								array(
									'key'               => 'field_606222213bd275',
									'label'             => 'Kampania',
									'name'              => 'campaign',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'campaign',
									),
									'taxonomy'          => '',
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_6062230f573c0',
					'label'             => 'Lista zalet',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'main-site-only'    => true,
				),
				array(
					'key'               => 'field_60622319573c1',
					'label'             => 'Lista zalet',
					'name'              => 'advantages-list',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062232c573c2',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '(max. 75 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 75,
						),
						array(
							'key'               => 'field_6062234f573c3',
							'label'             => 'Opis',
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => '(max. 160 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 160,
							'rows'              => '',
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_6062232c573c3',
							'label'             => 'Tekst przycisku do rozwijania list na urządzeniach mobilnych',
							'name'              => 'more-text',
							'type'              => 'text',
							'instructions'      => '(max. 75 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 75,
						),
						array(
							'key'               => 'field_60622380573c4',
							'label'             => 'Punkty w lewej kolumnie',
							'name'              => 'list1',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622389573c5',
									'label'             => 'Tekst',
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions'      => '(max. 160 znaków)',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => 160,
									'rows'              => 4,
									'new_lines'         => '',
								),
							),
						),
						array(
							'key'               => 'field_60622380ad3c4',
							'label'             => 'Punkty w prawej kolumnie',
							'name'              => 'list2',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622389573c5',
									'label'             => 'Tekst',
									'name'              => 'text',
									'type'              => 'textarea',
									'instructions'      => '(max. 160 znaków)',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'maxlength'         => 160,
									'rows'              => 4,
									'new_lines'         => '',
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606223ac573c6',
					'label'             => 'Formularz',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
					'main-site-only'    => true,
				),
				array(
					'key'               => 'field_606223e8573c7',
					'label'             => 'Formularz',
					'name'              => 'form',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'main-site-only'    => true,
					'sub_fields'        => array(
						array(
							'key'               => 'field_606223fe573c8',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => 'Domyślnie tekst nagłówka jest w kolorze szarym. <br>Aby dana fraza była w kolorze czarnym, proszę umieścić ją pomiędzy &lt;strong>&lt;/strong&gt; , np. &lt;strong>TEKST&lt;/strong&gt;. <br>Aby dodać przejście do kolejnej lini proszę dodać &lt;br> np. TEKST &lt;br>TEKST',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6062242c573c9',
							'label'             => 'Modele do wyboru',
							'name'              => 'models',
							'type'              => 'repeater',
							'instructions'      => 'Wszystkie modele Volvo dostępne do wyboru przy wypełnianiu formularza',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622460573ca',
									'label'             => 'Nazwa',
									'name'              => 'name',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
							),
						),
						array(
							'key'               => 'field_606224c3573cb',
							'label'             => 'Usługi',
							'name'              => 'services',
							'type'              => 'repeater',
							'instructions'      => 'Wszystkie usługi dostępne do wyboru przy wypełnianiu formularza',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_606224de573cc',
									'label'             => 'Ikona',
									'name'              => 'icon',
									'type'              => 'icon_select',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'choices'           => IconsDictionary::getIcons(),
									'default_value'     => false,
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'value',
									'ui'                => 1,
									'ajax'              => 0,
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_606224f2573cd',
									'label'             => 'Nazwa',
									'name'              => 'name',
									'type'              => 'text',
									'instructions'      => '(max. 75 znaków)',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 75,
								),
								array(
									'key'               => 'field_60622500573ce',
									'label'             => 'Opis',
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'visual',
									'toolbar'           => 'blog',
									'media_upload'      => 1,
									'delay'             => 0,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_606225ef573cf',
					'label'             => 'Usługi serwisowe',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60622604573d0',
					'label'             => 'Usługi serwisowe',
					'name'              => 'services-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062261c573d1',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'main-site-only'    => true,
						),
						array(
							'key'               => 'field_6062262b573d2',
							'label'             => 'Usługi',
							'name'              => 'services',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'row',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6062264a573d3',
									'label'             => 'Tytuł',
									'name'              => 'heading',
									'type'              => 'text',
									'instructions'      => '(max. 75 znaków)',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => 75,
								),
								array(
									'key'               => 'field_60622659573d4',
									'label'             => 'Opis',
									'name'              => 'description',
									'type'              => 'wysiwyg',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'tabs'              => 'visual',
									'toolbar'           => 'blog',
									'media_upload'      => 1,
									'delay'             => 0,
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_60622673573d5',
					'label'             => 'Kontakt z serwisem',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_60622681573d6',
					'label'             => 'Kontakt z serwisem',
					'name'              => 'contact-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6062268d573d7',
							'label'             => 'Nagłówek',
							'name'              => 'heading',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'main-site-only'    => true,
						),
						array(
							'key'               => 'field_606226d4573d8',
							'label'             => 'Osoby kontaktowe',
							'name'              => 'employees',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => '',
							'child-site-only'   => true,
							'sub_fields'        => array(
								array(
									'key'               => 'field_60622708573d9',
									'label'             => 'Specjalizacje',
									'name'              => 'specializations',
									'type'              => 'repeater',
									'instructions'      => '(max. 3 specjalizacje)',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 0,
									'max'               => 3,
									'layout'            => 'table',
									'button_label'      => '',
									'sub_fields'        => array(
										array(
											'key'          => 'field_6062273e573da',
											'label'        => 'Nazwa specjalizacji',
											'name'         => 'name',
											'type'         => 'text',
											'instructions' => '(max. 22 znaki)',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => 22,
										),
									),
								),
								array(
									'key'               => 'field_60622763573db',
									'label'             => 'Pracownik',
									'name'              => 'employee',
									'type'              => 'post_object',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'post_type'         => array(
										0 => 'employee',
									),
									'allow_null'        => 0,
									'multiple'          => 0,
									'return_format'     => 'id',
									'ui'                => 1,
								),
							),
						),
					),
				),
				array(
					'key'               => 'vinomat_boxes',
					'label'             => 'Boxy ofertowe',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'vinomat_boxes_section',
					'label'             => 'Kontakt z serwisem',
					'name'              => 'vinomat-section',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'vinomat_news_dealer',
							'label'             => 'Vinomat boks informacyjny',
							'name'              => 'vinomat_news',
							'type'              => 'repeater',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'         => '',
							'min'               => 0,
							'max'               => 3,
							'layout'            => 'table',
							'button_label'      => '',
							'sub_fields'        => array(
								array(
									'key'               => 'vinomat_news_title',
									'label'             => 'Tytuł',
									'name'              => 'vinomat_news_title',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'vinomat_news_desc',
									'label'             => 'Opis',
									'name'              => 'vinomat_news_desc',
									'type'              => 'textarea',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'vinomat_news_image',
									'label'             => 'Zdjęcie',
									'name'              => 'vinomat_news_image',
									'type'              => 'image',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'return_format'     => 'integer',
									'preview_size'      => 'small',
									'library'           => 'all',
									'min_width'         => '',
									'min_height'        => '',
									'min_size'          => '',
									'max_width'         => '',
									'max_height'        => '',
									'max_size'          => '',
									'mime_types'        => '',
								),
								array(
									'key'               => 'vinomat_box_link',
									'label'             => 'Link do kampani',
									'name'              => 'slides',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 1,
									'layout'            => 'row',
									'button_label'      => 'Dodaj kampanię',
									'sub_fields'        => array(
										array(
											'key'          => 'vinomat_box_link_type',
											'label'        => 'Typ kampanii',
											'name'         => 'type',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'local'  => 'Kampania lokalna',
												'global' => 'Kampania globalna',
											),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
										),
										array(
											'key'          => 'vinomat_box_link_type_1',
											'label'        => 'Kampania',
											'name'         => 'local-campaign',
											'type'         => 'post_object',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'vinomat_box_link_type',
														'operator' => '==',
														'value'    => 'local',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => 'campaign',
											),
											'taxonomy'     => '',
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'id',
											'ui'           => 1,
										),
										array(
											'key'          => 'vinomat_box_link_type_2',
											'label'        => 'Kampania',
											'name'         => 'global-campaign',
											'type'         => 'network_post_object',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => array(
												array(
													array(
														'field'    => 'vinomat_box_link_type',
														'operator' => '==',
														'value'    => 'global',
													),
												),
											),
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'post_type'    => array(
												0 => 'campaign',
											),
											'taxonomy'     => '',
											'allow_null'   => 0,
											'multiple'     => 0,
											'return_format' => 'id',
											'ui'           => 1,
										),
									),
								),
							),
						),
					),
				),
				array(
					'key' => 'service_additional',
					'label' => 'Dodatkowe ustawienia',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'service_additional_section',
					'label' => 'Kod do podstrony z podziękowaniem',
					'name' => 'service-section',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_thankyou_code',
							'label' => 'Dodatkowy kod na podstronie z podziękowaniem',
							'name' => 'field_thankyou_code',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'options-service',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'autoload' => true,
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);
endif;
