<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :
	acf_add_local_field_group(
		array(
			'key'                   => 'group_6051cd52bb16f',
			'title'                 => 'Salon',
			'fields'                => array(
				array(
					'key'               => 'field_6051cfffc4f4e',
					'label'             => 'Informacje podstawowe',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051cd9117f12',
					'label'             => 'ID salonu',
					'name'              => 'showroomId',
					'type'              => 'text',
					'instructions'      => 'Pełne showroomId dealerstwa np. <strong>PL100#1</strong>',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'admin-only'        => true,
				),
				array(
					'key'               => 'field_60b4d37267g4d',
					'label'             => 'Posiada salon',
					'name'              => 'has-showroom',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => true,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60b4d37267f4d',
					'label'             => 'Posiada serwis',
					'name'              => 'has-service',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_60b4d37267f4f',
					'label'             => 'Posiada Biuro Obsługi Klienta',
					'name'              => 'has-customer-service-office',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
				array(
					'key'               => 'field_6051cd8117f12',
					'label'             => 'Nazwa salonu',
					'name'              => 'name',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'required-multi-showroom-and-service-only' => true,
				),
				array(
					'key'               => 'field_6051cd8c17f13',
					'label'             => 'Adres',
					'name'              => 'address',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051cda717f14',
							'label'             => 'Ulica',
							'name'              => 'street',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6051cdb317f15',
							'label'             => 'Kod pocztowy',
							'name'              => 'zip-code',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => 'xx-xxx',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => 6,
						),
						array(
							'key'               => 'field_6051ce5217f16',
							'label'             => 'Miasto',
							'name'              => 'city',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_6051ce6317f17',
							'label'             => 'Nr telefonu',
							'name'              => 'phone',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051cf3117f20',
					'label'             => 'Pozycja na mapie',
					'name'              => 'map-position',
					'type'              => 'google_map',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'center_lat'        => '51.9194',
					'center_lng'        => '19.1451',
					'zoom'              => '6',
					'height'            => '',
				),
				array(
					'key'               => 'field_6051cd8117f22',
					'label'             => 'Miejscowość salonu',
					'name'              => 'showroom-location',
					'type'              => 'text',
					'instructions'      => 'Miejscowość salonu, która będzie użyta na stronie odreki.poznajvolvo.pl',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'admin-only'        => true,
				),
				array(
					'key'               => 'field_6051d00bc4f4f',
					'label'             => 'Godziny otwarcia salonu',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267g4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051ce7917f18',
					'label'             => 'Godziny otwarcia salonu',
					'name'              => 'showroom-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267g4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051ce9c17f19',
							'label'             => 'Poniedziałek-piątek',
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa1a6ee2b',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa2f6ee2c',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa426ee2d',
							'label'             => 'Sobota',
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa426ee2e',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa426ee2f',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051cee517f1b',
							'label'             => 'Dodatkowe informacje',
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions'      => '(max. 100 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051d018c4f50',
					'label'             => 'Godziny otwarcia serwisu',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051fa4c6ee30',
					'label'             => 'Godziny otwarcia serwisu',
					'name'              => 'service-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4d',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051fa4c6ee31',
							'label'             => 'Poniedziałek-piątek',
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa4c6ee32',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa4c6ee33',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa4c6ee34',
							'label'             => 'Sobota',
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051fa4c6ee35',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051fa4c6ee36',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051fa4c6ee37',
							'label'             => 'Dodatkowe informacje',
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions'      => '(max. 100 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_6051d018c4f51',
					'label'             => 'Godziny otwarcia Biura Obsługi Klienta',
					'name'              => '',
					'type'              => 'tab',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4f',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'placement'         => 'top',
					'endpoint'          => 0,
				),
				array(
					'key'               => 'field_6051d018c4f52',
					'label'             => 'Godziny otwarcia Biura Obsługi Klienta',
					'name'              => 'customer-service-office-open-hours',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_60b4d37267f4f',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6051d018c4f53',
							'label'             => 'Poniedziałek-piątek',
							'name'              => 'monday-friday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051d018c4f54',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051d018c4f55',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051d018c4f56',
							'label'             => 'Sobota',
							'name'              => 'saturday',
							'type'              => 'group',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '50',
								'class' => '',
								'id'    => '',
							),
							'layout'            => 'table',
							'sub_fields'        => array(
								array(
									'key'               => 'field_6051d018c4f57',
									'label'             => 'Od',
									'name'              => 'from',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
								array(
									'key'               => 'field_6051d018c4f58',
									'label'             => 'Do',
									'name'              => 'to',
									'type'              => 'time_picker',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '50',
										'class' => '',
										'id'    => '',
									),
									'display_format'    => 'H:i:s',
									'return_format'     => 'H:i:s',
								),
							),
						),
						array(
							'key'               => 'field_6051d018c4f59',
							'label'             => 'Dodatkowe informacje',
							'name'              => 'additional-info',
							'type'              => 'textarea',
							'instructions'      => '(max. 100 znaków)',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => 100,
							'rows'              => 3,
							'new_lines'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'showroom',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'discussion',
				4  => 'comments',
				5  => 'slug',
				6  => 'author',
				7  => 'format',
				8  => 'page_attributes',
				9  => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
			'active'                => true,
			'description'           => '',
		)
	);
endif;
