<?php


if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_603cee7231e0c',
        'title' => 'TwoColumnContentComponent',
        'fields' => array(
            array(
                'key' => 'field_603cee7eb259a',
                'label' => 'Zdjęcie',
                'name' => 'img',
                'type' => 'image',
                'instructions' => 'Należy sprawdzić czy wysokość treści nie przewyższa wysokości obrazka<br>(min. szerokość 959px, Zalecana szerokość: 2877px)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'integer',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_603ceef6167bd',
                'label' => 'Video',
                'name' => 'video',
                'type' => 'text',
                'instructions' => 'Link do filmu w serwisie youtube.com<br> Np. https://www.youtube.com/watch?v=LXb3EKWsInQ&t=4s',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_6074604797816',
                'label' => 'Szerokość obrazka',
                'name' => 'image-width',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    50 => '1/2',
                    70 => '2/3',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 70,
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_6074609197817',
                'label' => 'Pozycja obrazka',
                'name' => 'image-position',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Lewo',
                    'right' => 'Prawo',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'left',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_603ceec1b259c',
                'label' => 'Podtytuł',
                'name' => 'subheading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_603ceec9b259d',
                'label' => 'Nagłówek',
                'name' => 'heading',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_605de527d4054',
                'label' => 'Zawartość',
                'name' => 'content',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_605de535462fa' => array(
                        'key' => 'layout_605de535462fa',
                        'name' => 'description',
                        'label' => 'Opis',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de542d4055',
                                'label' => 'Opis',
                                'name' => 'description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de54bd4056' => array(
                        'key' => 'layout_605de54bd4056',
                        'name' => 'contact-info',
                        'label' => 'Osoba kontaktowa',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de569d4057',
                                'label' => 'Osoba kontaktowa',
                                'name' => 'contact-info',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'employee',
                                ),
                                'taxonomy' => '',
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'id',
                                'ui' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de587d4058' => array(
                        'key' => 'layout_605de587d4058',
                        'name' => 'list',
                        'label' => 'Lista zalet',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de5a1d4059',
                                'label' => 'Lista zalet',
                                'name' => 'list',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_605de5acd405a',
                                        'label' => 'Tekst',
                                        'name' => 'text',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de5b2d405b' => array(
                        'key' => 'layout_605de5b2d405b',
                        'name' => 'link',
                        'label' => 'Przycisk',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de5c1d405d',
                                'label' => 'Akcja przycisku',
                                'name' => 'buttonAction',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'link' => 'Link',
                                    'form' => 'Formularz',
                                ],
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'return_format' => 'value',
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_605de5c1d405e',
                                'label' => 'Tekst przycisku',
                                'name' => 'buttonText',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_605de5c1d405d',
                                            'operator' => '==',
                                            'value' => 'form',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => 30,
                            ),
                            array(
                                'key' => 'field_605de5c1d405c',
                                'label' => 'Link',
                                'name' => 'link',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_605de5c1d405d',
                                            'operator' => '==',
                                            'value' => 'link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_605de5d5d405d' => array(
                        'key' => 'layout_605de5d5d405d',
                        'name' => 'table',
                        'label' => 'Tabela',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_605de5dbd405e',
                                'label' => 'Tabela',
                                'name' => 'table',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_605de5e4d405f',
                                        'label' => 'Etykieta',
                                        'name' => 'label',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_605de65fd4060',
                                        'label' => 'Wartość',
                                        'name' => 'value',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
						'layout_price_from' => array(
							'key' => 'layout_price_from',
							'name' => 'price_from',
							'label' => 'Cena od',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'price_from_group',
									'label' => 'Cena od',
									'name' => 'price_from_group',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 1,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'price_from_text',
											'label' => 'Tekst',
											'name' => 'price_from_text',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => 10,
										),
										array(
											'key' => 'field_price',
											'label' => 'Cena',
											'name' => 'field_price',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => 20,
										),
									),
								),
							),
							'min' => '',
							'max' => 1,
						),
                ),
                'button_label' => 'Dodaj zawartość',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/two-column-content-component',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
