<?php

namespace Tests\Classes;

use Classes\StockCarQueryBuilder;
use PHPUnit\Framework\TestCase;

class StockCarQueryBuilderTest extends TestCase {

	private $queryBuilder;

	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->queryBuilder = new StockCarQueryBuilder();
	}

	public function testNoFilters(): void {
		$query = $this->queryBuilder->build( array() );

		self::assertEquals( array(), $query );
	}

	public function testModelFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'model' => array( 'XC90', 'XC60' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'model',
					'value'   => array( 'XC90', 'XC60' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testColorFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'color' => array( 'gray', 'red' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'color',
					'value'   => array( 'gray', 'red' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testNoApplyUnknownFilters(): void {
		$query = $this->queryBuilder->build(
			array(
				'color'   => array( 'gray', 'red' ),
				'unknown' => array( '123' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'color',
					'value'   => array( 'gray', 'red' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testModelAndColorFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'color' => array( 'gray', 'red' ),
				'model' => array( 'XC90', 'XC60' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'color',
					'value'   => array( 'gray', 'red' ),
					'compare' => 'IN',
				),
				array(
					'key'     => 'model',
					'value'   => array( 'XC90', 'XC60' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testEngineFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'engine' => array( 'B4', 'B5 AWD' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'engine',
					'value'   => array( 'B4', 'B5 AWD' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testVersionFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'version' => array( 'Inscription', 'R-Design' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'version',
					'value'   => array( 'Inscription', 'R-Design' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testInlayFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'inlay' => array( 'skórzana', 'materiał' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'inlay',
					'value'   => array( 'skórzana', 'materiał' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testGearBoxFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'gearbox' => array( 'automatyczna', 'manualna' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'gearbox',
					'value'   => array( 'automatyczna', 'manualna' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testSingleMaxPowerFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'max-power' => array( '200-250' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'max-power',
					'value'   => array( '200', '250' ),
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				),
			),
			$query
		);
	}

	public function testMultipleMaxPowerFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'max-power' => array( '200-250', '300-400' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'relation' => 'OR',
					array(
						'key'     => 'max-power',
						'value'   => array( '200', '250' ),
						'type'    => 'numeric',
						'compare' => 'BETWEEN',
					),
					array(
						'key'     => 'max-power',
						'value'   => array( '300', '400' ),
						'type'    => 'numeric',
						'compare' => 'BETWEEN',
					),
				),
			),
			$query
		);
	}

	public function testProductionYearFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'production-year' => array( '2020', '2019' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'production-year',
					'value'   => array( '2020', '2019' ),
					'compare' => 'IN',
				),
			),
			$query
		);
	}

	public function testPriceRangeFilter(): void {
		$query = $this->queryBuilder->build(
			array(
				'discount-price' => array( '50000', '100000' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'discount-price',
					'value'   => array( '50000', '100000' ),
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				),
			),
			$query
		);
	}

	public function testShowroomAll(): void {
		$query = $this->queryBuilder->build(
			array(
				'showroom' => 'all',
			)
		);

		self::assertEquals(
			array(),
			$query
		);
	}

	public function testShowroom(): void {
		$query = $this->queryBuilder->build(
			array(
				'showroom' => 'malta-showroom',
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'showroom',
					'value'   => 'malta-showroom',
					'compare' => '=',
				),
			),
			$query
		);
	}

	public function testModelWithPriceRangeWithMaxPower(): void {
		$query = $this->queryBuilder->build(
			array(
				'model'          => array( 'XC90', 'XC60' ),
				'max-power'      => array( '200-250', '300-400' ),
				'discount-price' => array( '50000', '100000' ),
			)
		);

		self::assertEquals(
			array(
				array(
					'key'     => 'model',
					'value'   => array( 'XC90', 'XC60' ),
					'compare' => 'IN',
				),
				array(
					'relation' => 'OR',
					array(
						'key'     => 'max-power',
						'value'   => array( '200', '250' ),
						'type'    => 'numeric',
						'compare' => 'BETWEEN',
					),
					array(
						'key'     => 'max-power',
						'value'   => array( '300', '400' ),
						'type'    => 'numeric',
						'compare' => 'BETWEEN',
					),
				),
				array(
					'key'     => 'discount-price',
					'value'   => array( '50000', '100000' ),
					'type'    => 'numeric',
					'compare' => 'BETWEEN',
				),
			),
			$query
		);
	}
}
